### ISSUE TITLE
Allow early_stopping_nbest = 1

### ISSUE THREAD

**Issue by jeanm** [Calamari-OCR/calamari#101]
https://github.com/Calamari-OCR/calamari/blob/69e9c76368c3deba013de27a1f9918dc7f3aaf2e/calamari_ocr/ocr/trainer.py#L238-L240

Shouldn't users be able to set `--early_stopping_nbest` to 1?

If I'm just building a quick and dirty model to help me annotate extra training data, I don't usually care about squeezing out the last half percentage of accuracy, so I'm usually looking for a very aggressive early stop criterion.

**Comment by ChWick** [comment]
Currently, Calamari starts the best model counting at 1, that is, if Calamari checks for a new model, this model gets `nbest = 1`:
```python
if accuracy > early_stopping_best_accuracy:
    early_stopping_best_accuracy = accuracy
    early_stopping_best_cur_nbest = 1    # here, the initial model gets nbest=1
    early_stopping_best_at_iter = iter + 1
```
Therefore, if you set early_stopping_nbest to 1, it will immediately stop which, however, is not desired:
```
# If nbest == 1 and early_stopping_best == 1, the training will stop immediately
if accuracy > 0 and early_stopping_best_cur_nbest >= checkpoint_params.early_stopping_nbest:
    print("Early stopping now.")
    break
```
I could either change the initial test to 0 or you must set `--early_stopping_nbest` to 2 to tell Calamari, that if a model is the best model a second time, stop the training process.

Thus, `--early_stopping_nbest 2` should already be your desideratum.

**Comment by jeanm** [comment]
Ah, should've read the code more carefully, sorry. I do think having to set `--early_stopping_nbest 2` for "stop as soon as performance gets worse" is a bit counter-intuitive, but that's just a matter of taste. Thanks for the quick response.
