### ISSUE TITLE
No text recognized in very simply alphabet image

### ISSUE THREAD

**Issue by Stephanehk** [Calamari-OCR/calamari#104]
I just installed calamari and attempted to use `calamari-predict` on a very simple alphabet image (shown below). I used `--checkpoint calamari_models/antiqua_modern/*.ckpt`. No text was recognized by calamari and the text confidence was 0%, however, no errors were found.

![Imgur](https://i.imgur.com/XI1mVv3.gif)

To install calameri I used `pip install calamari_ocr` on my Mac OSX Sierra 10.12.6. I had a few warnings when running `calamari-predict`. Most of them were Tenserflow depreciation warnings as well as `I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA`. 

I was wondering what the problem could be. Thanks!

**Comment by ChWick** [comment]
Calamari does not full OCR pipeline since it acts on single line images. You need to split the paragraph into single lines first, then feed them into Calamari. For line splitting you can try the `gpageseg` script of [ocropus](https://github.com/tmbdev/ocropy).

**Comment by Stephanehk** [comment]
Thanks! I b
