### ISSUE TITLE
Add tensorflow to package dependencies

### ISSUE THREAD

**Issue by wrznr** [Calamari-OCR/calamari#105]
Proceeding as documented (i.e. `virtualenv` & `pip install clamari-ocr`) does not install `tensorflow` resulting in
```shell
(env) $ calamari-predict --checkpoint ~/calamari_models/fraktur_19th_century/4.ckpt --files test.jpg 
Found 1 files in the dataset
Upgrading from version 0
   ...
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'
```

**Comment by ChWick** [comment]
Thanks, I updated the README accordingly. Tensorflow must be installed manually since the user hast to decide whether to install `tensorflow` or `tensorflow_gpu` for gpu support.
