### ISSUE TITLE
Prediction with "fraktur_19th_century/4.ckpt" results in empty text

### ISSUE THREAD

**Issue by wrznr** [Calamari-OCR/calamari#106]
Using the following invocation of `calamari` does not produce any text for the image:
![region0001_line0002](https://user-images.githubusercontent.com/26707219/59099294-060eba80-8923-11e9-9cc3-d02529d02bc9.png)

```shell
calamari-predict --checkpoint calamari_models/fraktur_19th_century/4.ckpt --files region0001_line0002.png
```

Most likely, I am doing something wrong. It would be great if you could help me.

**Comment by ChWick** [comment]
`calamari_models/fraktur_19th_century` was trained on binary data (not on gray/colour), please use binarised lines (missing docs for the pretrained model...) and report if the model is working

**Comment by wrznr** [comment]
Many thanks for your fast replies! Using `nlbin`-generated
![region0001_line0002 bin](https://user-images.githubusercontent.com/26707219/59100171-8c2c0080-8925-11e9-9331-b6c350c10eb0.png)
results in
> dom kriegeriſchen Berufe zugewendet; 1843 war er Ofſizier geworden, aber auch hiſloriſche und

Any further hints on increasing the text quality?

**Comment by ChWick** [comment]
I suggest/try the following
* a higher image resolution (min line height of 48px, your example line is only 15px)
* white padding of 3px when using a line height of 48px, i.e. approx 1px padding in your 15px height image
* Voting: calamari-predict --checkpoint calamari_models/fraktur_19th_century/*.ckpt.json --files region0001_line0002.png

**Comment by wrznr** [comment]
Voting does the trick (should have known from reading your papers):
> dem kriegeriſchen Berufe zugewendet; 1843 war er Offizier geworden; aber auch hiſtoriſche und
