### ISSUE TITLE
Checkpoint not provided

### ISSUE THREAD

**Issue by raviteja8484** [Calamari-OCR/calamari#11]
![capture](https://user-images.githubusercontent.com/38815388/43901459-2da21562-9c05-11e8-9269-9a5727662cf7.PNG)

Can someone help me resolve this issue?

**Comment by ChWick** [comment]
replace the path_to_model.ckpt with an actual model (some pretrained models can be found e.g. here: https://github.com/Calamari-OCR/calamari_models)

**Comment by christophered** [comment]
@raviteja8484 when you train or use a model, it consists of 4 files, therefore put those 4 files in the folder where you start the terminal. Also when using the `--checkpoint` use your model .json file.
@raviteja8484 please re-test, and reply back

**Comment by MrOCR** [comment]
@raviteja8484 the solution to `No checkpoints provided` is to use `--checkpoint model.ckpt.json`
Currently, each model consists of 4 files, so you need those 4 files in the same folder:
```
model.ckpt.meta
model.ckpt.json
model.ckpt.index
model.ckpt.data-...
```
@ChWick please close this issue.

**Comment by hsl20130659** [comment]
File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1768, in __init__
    self._traceback = tf_stack.extract_stack()

NotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key cnn_lstm/B not found in checkpoint
	 [[{{node save_1/RestoreV2}} = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_1/Const_0_0, save_1/RestoreV2/tensor_names, save_1/RestoreV2/shape_and_slices)]]

how can I solve this problem?

**Comment by hsl20130659** [comment]
> @hsl20130659
> Christian have already updated the models in that repository which I have tested & are functioning properly, you can re-download them.
> 
> Download [this zip archive](https://ufile.io/3c9ti) and extract it in a folder, then run the terminal in that folder:
> 
> ```
Found 1 files in the dataset
/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-10-15 19:06:14.487920: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
Using CUDNN compatible LSTM backend on CPU
Loading Dataset: 100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00, 56.35it/s]
Data Preprocessing:   0%|                                                      | 0/1 [00:00<?, ?it/s]

I download the models again and do not update, but it stop here (data processing 0%),if updates ,the old problem  still exits.

**Comment by ChWick** [comment]
@hsl20130659 You dont need to updated the models, because they are successfully loaded. The following preprocessing step seems to cause an error. Do you receive any error message?

**Comment by MrOCR** [comment]
@hsl20130659 hmmm... my guess is that you didn't install the dependencies correctly.
I'd suggest that you create the calamari-ocr environment using **[environment_master_cpu.yml](https://github.com/Calamari-OCR/calamari/blob/master/environment_master_cpu.yml)** just download this file, and the type in the terminal:
```
conda env create -f environment_master_cpu.yml
```
Then re-test using the zip archive, and reply back.
