### ISSUE TITLE
Format of a groundtruth  json file

### ISSUE THREAD

**Issue by SumanthAmpcus** [Calamari-OCR/calamari#111]
Hi ,

I am generating my own dataset for training , as per your code groundtruth file has to be a txt file.

What is the format for the  ground truth file. Is it possible to include any more information apart from the actual data in the ground truth file?

Thanks

Sumanth

**Comment by ChWick** [comment]
Hi,

json files can not be used as GT files. A list of supported files/dataset formats (.txt, PageXML, Abbyy-XML, HDF5) is listed in the [wiki](https://github.com/Calamari-OCR/calamari/wiki/Dataset-formats) pages.
The most simple format is probably the ".png/.gt.txt" combination.

json-files can be used to define the parameters of the Calamari command line interfaces.
