### ISSUE TITLE
Error: Process finished with code 1 in cross-fold 

### ISSUE THREAD

**Issue by cornerman57** [Calamari-OCR/calamari#115]
It worked with the new code BUT after the fold 0 is done and found no better model than the 99,056858 I again get an error

FOLD 0 | Storing checkpoint to 'I:\BIQE\CALAMARI\projects\voetius\TRAINING\crosstrainen\fold_0\model_00019470.ckpt'
FOLD 0 | Checking early stopping model
Prediction: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1948/1948 [04:06<00:00,  6.38it/s]
FOLD 0 | No better model found. Currently accuracy of 99.056858% at iter 11682 (remaining nbest = 0)
FOLD 0 | Early stopping now.
FOLD 0 | Total time 11274.687343358994s for 19469 iterations.
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "c:\users\drsjh\anaconda3\envs\calamaridev\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "c:\users\drsjh\anaconda3\envs\calamaridev\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "c:\users\drsjh\anaconda3\envs\calamaridev\lib\site-packages\calamari_ocr\ocr\cross_fold_trainer.py", line 27, in train_individual_model
    ], args.get("run", None), {"threads": args.get('num_threads', -1)}), verbose=args.get("verbose", False)):
  File "c:\users\drsjh\anaconda3\envs\calamaridev\lib\site-packages\calamari_ocr\utils\multiprocessing.py", line 87, in run
    raise Exception("Error: Process finished with code {}".format(process.returncode))
Exception: Error: Process finished with code 1
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\drsjh\anaconda3\envs\calamaridev\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\drsjh\anaconda3\envs\calamaridev\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\drsjh\Anaconda3\envs\calamaridev\Scripts\calamari-cross-fold-train.exe\__main__.py", line 9, in <module>
  File "c:\users\drsjh\anaconda3\envs\calamaridev\lib\site-packages\calamari_ocr\scripts\cross_fold_train.py", line 80, in main
    temporary_dir=args.temporary_dir, keep_temporary_files=args.keep_temporary_files,
  File "c:\users\drsjh\anaconda3\envs\calamaridev\lib\site-packages\calamari_ocr\ocr\cross_fold_trainer.py", line 151, in run
    pool.map_async(train_individual_model, run_args).get()
  File "c:\users\drsjh\anaconda3\envs\calamaridev\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
Exception: Error: Process finished with code 1

**Comment by ChWick** [comment]
Unfortunately, I cannot reproduce this on my Windows machine using python 3.6.6:
```
FOLD 1 |  TRUE: '‪(a) Shmathematics. Initially, we use some‬'
FOLD 1 | #00000530: loss=14.10168618 ler=0.07942029 dt=0.81701994s
FOLD 1 |  PRED: '‪fro the point of rie of applications: Any‬'
FOLD 1 |  TRUE: '‪from the point of view of applications: Any‬'
FOLD 1 | #00000540: loss=13.89046135 ler=0.07986023 dt=0.82311377s
FOLD 1 |  PRED: '‪algorith that is usually ot very efficient.‬'
FOLD 1 |  TRUE: '‪algorithm that is usually not very efficient.‬'
FOLD 1 | Checking early stopping model
Prediction: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:01<00:00,  7.75it/s]
FOLD 1 | No better model found. Currently accuracy of 87.870620% at iter 500 (remaining nbest = 0)
FOLD 1 | Early stopping now.
FOLD 1 | Total time 508.6043953895569s for 549 iterations.
Executing: C:\Users\wick\Anaconda3\envs\calamari\python.exe -u C:\Users\wick\PycharmProjects\calamari\calamari_ocr\scripts\train.py --files C:\Users\wick\AppData\Local\Temp\calamari5vp6ml_h\fold_2.json
FOLD 2 | Resolving input files
FOLD 2 | Found 40 files in the dataset
FOLD 2 | Resolving validation files
FOLD 2 | Found 10 files in the validation dataset
FOLD 2 | Preloading dataset type DataSetMode.TRAIN with size 40
```

Maybe this is related to a different python version? Which version are you using?

**Comment by cornerman57** [comment]
3.6.6 version

Van: ChWick <notifications@github.com>
Verzonden: woensdag 26 juni 2019 14:20
Aan: Calamari-OCR/calamari <calamari@noreply.github.com>
CC: cornerman57 <drsjhoekman@outlook.com>; Author <author@noreply.github.com>
Onderwerp: Re: [Calamari-OCR/calamari] Error: Process finished with code 1 in cross-fold (#115)


Unfortunately, I cannot reproduce this on my Windows machine using python 3.6.6:

FOLD 1 |  TRUE: '‪(a) Shmathematics. Initially, we use some'



FOLD 1 | #00000530: loss=14.10168618 ler=0.07942029 dt=0.81701994s



FOLD 1 |  PRED: '‪fro the point of rie of applications: Any'



FOLD 1 |  TRUE: '‪from the point of view of applications: Any'



FOLD 1 | #00000540: loss=13.89046135 ler=0.07986023 dt=0.82311377s



FOLD 1 |  PRED: '‪algorith that is usually ot very efficient.'



FOLD 1 |  TRUE: '‪algorithm that is usually not very efficient.'



FOLD 1 | Checking early stopping model



Prediction: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:01<00:00,  7.75it/s]



FOLD 1 | No better model found. Currently accuracy of 87.870620% at iter 500 (remaining nbest = 0)



FOLD 1 | Early stopping now.



FOLD 1 | Total time 508.6043953895569s for 549 iterations.



Executing: C:\Users\wick\Anaconda3\envs\calamari\python.exe -u C:\Users\wick\PycharmProjects\calamari\calamari_ocr\scripts\train.py --files C:\Users\wick\AppData\Local\Temp\calamari5vp6ml_h\fold_2.json



FOLD 2 | Resolving input files



FOLD 2 | Found 40 files in the dataset



FOLD 2 | Resolving validation files



FOLD 2 | Found 10 files in the validation dataset



FOLD 2 | Preloading dataset type DataSetMode.TRAIN with size 40



Maybe this is related to a different python version? Which version are you using?

**Comment by cornerman57** [comment]
Do I have a right training script line?


calamari-cross-fold-train --max_parallel_models=3 --temporary_dir=crosstrainen --files voetius200/????/*.png --best_models_dir bestmodelcross --early_stopping_nbest=5 --n_augmentation=3 --n_folds=3 --weights I:\BIQE\CALAMARI\projects\voetius\TRAINING\bestmodel\best.ckpt I:\BIQE\CALAMARI\calamari_models-master\calamari_models-master\antiqua_historical\0.ckpt I:\BIQE\CALAMARI\calamari_models-master\calamari_models-master\antiqua_historical\1.ckpt

Van: ChWick <notifications@github.com>
Verzonden: woensdag 26 juni 2019 14:20
Aan: Calamari-OCR/calamari <calamari@noreply.github.com>
CC: cornerman57 <drsjhoekman@outlook.com>; Author <author@noreply.github.com>
Onderwerp: Re: [Calamari-OCR/calamari] Error: Process finished with code 1 in cross-fold (#115)


Unfortunately, I cannot reproduce this on my Windows machine using python 3.6.6:

FOLD 1 |  TRUE: '‪(a) Shmathematics. Initially, we use some'



FOLD 1 | #00000530: loss=14.10168618 ler=0.07942029 dt=0.81701994s



FOLD 1 |  PRED: '‪fro the point of rie of applications: Any'



FOLD 1 |  TRUE: '‪from the point of view of applications: Any'



FOLD 1 | #00000540: loss=13.89046135 ler=0.07986023 dt=0.82311377s



FOLD 1 |  PRED: '‪algorith that is usually ot very efficient.'



FOLD 1 |  TRUE: '‪algorithm that is usually not very efficient.'



FOLD 1 | Checking early stopping model



Prediction: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:01<00:00,  7.75it/s]



FOLD 1 | No better model found. Currently accuracy of 87.870620% at iter 500 (remaining nbest = 0)



FOLD 1 | Early stopping now.



FOLD 1 | Total time 508.6043953895569s for 549 iterations.



Executing: C:\Users\wick\Anaconda3\envs\calamari\python.exe -u C:\Users\wick\PycharmProjects\calamari\calamari_ocr\scripts\train.py --files C:\Users\wick\AppData\Local\Temp\calamari5vp6ml_h\fold_2.json



FOLD 2 | Resolving input files



FOLD 2 | Found 40 files in the dataset



FOLD 2 | Resolving validation files



FOLD 2 | Found 10 files in the validation dataset



FOLD 2 | Preloading dataset type DataSetMode.TRAIN with size 40



Maybe this is related to a different python version? Which version are you using?

**Comment by ChWick** [comment]
The augmentation parameter is `--n_augmentations` (with a s), however, I wonder why it accepts it anyway. Could you try to set or omit `--n_augmentations` and test if this changes the training?

**Comment by ChWick** [comment]
And maybe try to train only one model in parallel for testing (`--max_parallel_models=1`)

**Comment by ChWick** [comment]
P. S. I just ran 
```
C:\Users\wick\Anaconda3\envs\calamari\python.exe -u calamari_ocr/scripts/cross_fold_train.py --files calamari_ocr/test/data/uw3_50lines/train/*.png --max_parallel_models=3 --temporary_dir=crosstrainen  --best_models_dir bestmodelcross --early_stopping_nbest=2 --n_augmentation=3 --n_folds=3
```
without any problems (with `max_parallel_models=3` and the "wrong" `--n_augmentation=3` parameter), however only with `_nbest=2`

**Comment by cornerman57** [comment]
After a long and intensive training of a few hours It still end with an error


FOLD 2 | #00025300: loss=0.94556467 ler=0.00461834 dt=0.07859938s
FOLD 2 |  PRED: '‪ſiaſticam ad practicas referimus. Addimus eſſe ſacram, ut ab aliis com-'
FOLD 2 |  TRUE: '‪ſiaſticam ad practicas referimus. Addimus eſſe ſacram, ut ab aliis com-'
FOLD 2 | Storing checkpoint to 'I:\BIQE\CALAMARI\projects\voetius\TRAINING\crosstrainen\fold_2\model_00025311.ckpt'
FOLD 2 | Checking early stopping model
Prediction: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1947/1947 [04:21<00:00,  5.39it/s]
FOLD 2 | No better model found. Currently accuracy of 99.023925% at iter 17523 (remaining nbest = 0)
FOLD 2 | Early stopping now.
FOLD 2 | Total time 22923.951451063156s for 25310 iterations.
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "c:\users\drsjh\anaconda3\envs\calamaridev\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "c:\users\drsjh\anaconda3\envs\calamaridev\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "c:\users\drsjh\anaconda3\envs\calamaridev\lib\site-packages\calamari_ocr\ocr\cross_fold_trainer.py", line 27, in train_individual_model
    ], args.get("run", None), {"threads": args.get('num_threads', -1)}), verbose=args.get("verbose", False)):
  File "c:\users\drsjh\anaconda3\envs\calamaridev\lib\site-packages\calamari_ocr\utils\multiprocessing.py", line 87, in run
    raise Exception("Error: Process finished with code {}".format(process.returncode))
Exception: Error: Process finished with code 1
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\drsjh\anaconda3\envs\calamaridev\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\drsjh\anaconda3\envs\calamaridev\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\drsjh\Anaconda3\envs\calamaridev\Scripts\calamari-cross-fold-train.exe\__main__.py", line 9, in <module>
  File "c:\users\drsjh\anaconda3\envs\calamaridev\lib\site-packages\calamari_ocr\scripts\cross_fold_train.py", line 80, in main
    temporary_dir=args.temporary_dir, keep_temporary_files=args.keep_temporary_files,
  File "c:\users\drsjh\anaconda3\envs\calamaridev\lib\site-packages\calamari_ocr\ocr\cross_fold_trainer.py", line 151, in run
    pool.map_async(train_individual_model, run_args).get()
  File "c:\users\drsjh\anaconda3\envs\calamaridev\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
Exception: Error: Process finished with code 1

(calamaridev) I:\BIQE\CALAMARI\projects\voetius\TRAINING>


Van: ChWick <notifications@github.com>
Verzonden: woensdag 26 juni 2019 15:45
Aan: Calamari-OCR/calamari <calamari@noreply.github.com>
CC: cornerman57 <drsjhoekman@outlook.com>; Author <author@noreply.github.com>
Onderwerp: Re: [Calamari-OCR/calamari] Error: Process finished with code 1 in cross-fold (#115)


P. S. I just ran

C:\Users\wick\Anaconda3\envs\calamari\python.exe -u calamari_ocr/scripts/cross_fold_train.py --files calamari_ocr/test/data/uw3_50lines/train/*.png --max_parallel_models=3 --temporary_dir=crosstrainen  --best_models_dir bestmodelcross --early_stopping_nbest=2 --n_augmentation=3 --n_folds=3

without any problems (with max_parallel_models=3 and the "wrong" --n_augmentation=3 parameter), however only with _nbest=2

**Comment by ChWick** [comment]
I hope I can reproduce this on an other windows machine. However, can you confirm that the crash occurs always at the end of all folds? If this is the case, all models are successfully trained and stored in `bestmodelcross` (there should be `n_folds` models), which you can use for prediction/evaluation/... Solely the "cleanup" crashes.

**Comment by cornerman57** [comment]
Yes I can confirm that its Always at the end of the proces

Wedis a prediction on two models And I made a script to see the average per page. My question is: Is the number per page I see an average of the two models? Or does it choose and take the best model for each letter/word?


PS I also want to train the Old Greek and the Hebrew some more. Do you have any tips?




Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

________________________________
Van: ChWick <notifications@github.com>
Verzonden: Friday, June 28, 2019 8:58:42 AM
Aan: Calamari-OCR/calamari
CC: cornerman57; Author
Onderwerp: Re: [Calamari-OCR/calamari] Error: Process finished with code 1 in cross-fold (#115)


I hope I can reproduce this on an other windows machine. However, can you confirm that the crash occurs always at the end of all folds? If this is the case, all models are successfully trained and stored in bestmodelcross (there should be n_folds models), which you can use for prediction/evaluation/... Solely the "cleanup" crashes.

**Comment by ChWick** [comment]
Unfortunately, I could not reproduce the crash even on other windows machines.

The best model is chosen on the validation data set that is, if you train two models, 50% of the training data you specified. Therefore, it the best model on average.

In our experiments a cross-fold-size of 5 yielded a good compromise between speed and efficiency. Also try to chose the best fitting pretrained model from the `calamari_models`.

**Comment by cornerman57** [comment]
I am training OLD GREEK from around 1600 But I am not getting any higher than 68%
Can you tell me how many pages I must have at least for a good training? If I understand well the percentages are 80% training and 20% validation.



Jannes Hoekman

Van: ChWick <notifications@github.com>
Verzonden: dinsdag 2 juli 2019 09:10
Aan: Calamari-OCR/calamari <calamari@noreply.github.com>
CC: cornerman57 <drsjhoekman@outlook.com>; Author <author@noreply.github.com>
Onderwerp: Re: [Calamari-OCR/calamari] Error: Process finished with code 1 in cross-fold (#115)


Unfortunately, I could not reproduce the crash even on other windows machines.

The best model is chosen on the validation data set that is, if you train two models, 50% of the training data you specified. Therefore, it the best model on average.

In our experiments a cross-fold-size of 5 yielded a good compromise between speed and efficiency. Also try to chose the best fitting pretrained model from the calamari_models.
