### ISSUE TITLE
line_height 50-79 give shapes mismatch error

### ISSUE THREAD

**Issue by ocrwork** [Calamari-OCR/calamari#127]
Thanks for this, which is the most awesome line ocr software I have seen anywhere!
setting line_height 50 in calamari_train gives error:
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 1000800 values, but the requested shape has 950760
	 [[{{node cnn_lstm_1/Reshape_1}}]]
line_height 48 goves no error.
line_height 50 up to 79 gives similar error.
line_height 80 and 200 also give no error.
This is all with image actual height 50px.
Can anyone tell me how to troubleshoot this problem?
I would like to display the network layer shapes, and know where the code that generates the network shapes is located, then I can look into it, can report on a solution.

**Comment by chreul** [comment]
the default network contains two 2x2 pooling operations, therefore the chosen line height has to be divisible by 4

**Comment by ocrwork** [comment]
Thanks, exactly so.
