### ISSUE TITLE
calamari-resume-training hangs

### ISSUE THREAD

**Issue by ocrwork** [Calamari-OCR/calamari#129]
I tried calamari-resume-training after hitting ctrl-c by mistake.
It does a reload shuffle buffer of 1000, then displays the loss, ler, dt numbers.
The dt is about 10 times what it usually is.
Then it takes a very long time, and displays the next stats (I had display=100)
this time, dt is about 20 times normal.
I waited a long time, like 20 minutes, and no other output came out.
top command shows 4 calamari-resume-training tasks using 100% cpu.
Not critical, but it would save some time if I can resume training.

**Comment by mrocr** [comment]
@ChWick @chreul this guy is interesting.

**Comment by ChWick** [comment]
Feel free to reopen if this issue is still persistent in Calamari 2.0
