### ISSUE TITLE
Confusing naming of the "checkpoint" file

### ISSUE THREAD

**Issue by mikegerber** [Calamari-OCR/calamari#130]
As far as I understand it, I can only give `*.ckpt.json` files as a `CHECKPOINT` parameter.

There is a `checkpoint` file in a model directory, too, but I cannot use it as a `CHECKPOINT`.

🤔

**Comment by ChWick** [comment]
The current Calamari version does not produce `checkpoint` files anymore due to upgrading to Tensorflow 2.
