### ISSUE TITLE
.

### ISSUE THREAD

**Issue by mrocr** [Calamari-OCR/calamari#136]
.

**Comment by wrznr** [comment]
@mrocr As a side note: You could combine the text-line detection from Tesseract or Kraken or Ocropus with Calamari's recognition (this is what I did to test Calamari's models).

**Comment by mrocr** [comment]
@wrznr That is not enough and you know it,
the open-source community have came a long way, of-which the most promising method is detecting the baselines, then detecting text-line polygons.
@Mittagessen; the developer of kraken, is working on such method.

My proposal is:
That I work on the baseline detection method.
While ChWick and Mittagessen team-up & focus on converting the detected base-lines into text-lines.

ChWick somehow keeps avoiding any topic that I even remotely mention layout analysis in it.
hmmmm.....

**Comment by wrznr** [comment]
@mrocr: Sounds promising!

**Comment by wrznr** [comment]
@mrocr https://github.com/OMMR4all/ommr4all-line-detection @ChWick is actually working on layout analysis (although in a slightly different context).

**Comment by mrocr** [comment]
@wrznr I spoke with @ChWick before regarding ommr4all, and I quote his reply"

> This project only aims to only detect staff lines, it is not intended to detect baselines of text

He only released a music sheet detection, not text-line.
I already researched, and chwick have done research in the matter of detecting text-lines and page-layouts using cnn's. My guess is that he already have a working text-line detector using cnn.

**Comment by mrocr** [comment]
@wrznr If I create the text-line detector on my own, trust me, it's most likely gonna be closed source.
:)
