### ISSUE TITLE
`token-passing-ctc` are you going for Aster?

### ISSUE THREAD

**Issue by deepseek** [Calamari-OCR/calamari#138]
@ChWick just saw the `token-passing-ctc` branch, are you aiming for [Aster](https://github.com/bgshih/aster)? 
or you're aiming for[ githubharald's algorithm](https://github.com/githubharald/CTCWordBeamSearch)?

**Comment by ChWick** [comment]
I'm using the python implementation of [githubharald](https://github.com/githubharald/CTCWordBeamSearch) (currently very slow). The goal is to provide a dictionary, or a complete language model (n-grams) when decoding text with a very bad accuracy (e.g., handwritten, or very old fonts).
