### ISSUE TITLE
Tensorflow contrib not found

### ISSUE THREAD

**Issue by varshaneya** [Calamari-OCR/calamari#139]
I have followed the installation instructions in the README file of this repo to install install using pip on Ubuntu. Below is the error I'm getting:

![calamari_error](https://user-images.githubusercontent.com/12171425/67845223-1ec37b00-fb25-11e9-9aae-6944893ac644.jpg)

The current version of tensorflow (2.0.0) donot have contrib package. Refer to this [link](https://www.tensorflow.org/guide/migrate#a_note_on_slim_contriblayers). But the code uses RNN from contrib. 

So I downgraded the tensorflow to 1.14.0, but unable to use the checkpoints as they are incompatible with  tensorflow 1.14.0.

My ubuntu version 18.04.

**Comment by ChWick** [comment]
I guess you installed calamari using `pip install calamari_ocr`. I forgot to update these packages to v1.0.0, but they should be available (and working with tf 2.0) now. To upgrade call:
```
pip install --upgrade calamari_ocr
```

Alternatively you can clone the repo and call `python setup.py install`.

Please check if this works for you!
