### ISSUE TITLE
How to predict calamari with multiple languages one time

### ISSUE THREAD

**Issue by a41888936** [Calamari-OCR/calamari#14]
I try to analyzed a image which containing both  Korean and English texts. 

How can I run one process which recognize both Korean and English characters?

I guess I got two options

1. Making dataset containing both Korean and English text images.

2. Using voting algorithm.

Am I right? 

Can you give me some advice??

**Comment by chreul** [comment]
the easiest solution is to train mixed models as you suggested in 1. this should work very well.

another solution would be to run a script identification (see Ul Hasan et al.: A Sequence Learning Approach for Multiple Script Identification) first an then classify the text with a script specific model. depending on your data this is probably the most precise solution but requires (a lot) of additional effort.

regarding the voting algorithm: i'm not sure if i understood you correctly but if your plan is to use 2/2 3/3 ... korean/english models and then perform a voting, i would advice against it.

**Comment by mittagessen** [comment]
Just as a note: You can easily convert training data for mixed models to script identification data. In my experience the sequence-learned script identification is less typeface-specific than character recognition models, so if you've got more than one typeface (that is potentially reused) it might be worth the effort.

Further, if the Korean accuracy is less than expected make sure not to mix precomposed (Hangul Syllables code block) and positional (Hangul Jamo) code points. The last models I trained didn't deal particularly well with that. Of course that is only an issue with non-modern Korean texts.

**Comment by a41888936** [comment]
@chreul  @mittagessen  thank you for your adivces. I trained model using eng+kor dataset. It seems not bad.

![img_2952](https://user-images.githubusercontent.com/24805731/44702066-7fdc6280-aacc-11e8-8e79-8962b217017e.JPG)

I preprocessed using ocropy script and some opencv stuff. 
Evaluation is below like 
Got mean normalized label error rate of 2.47% (16 errs, 648 total chars, 16 sync errs)
GT       PRED     COUNT    PERCENT   
{r}      {t}             7     43.75%
{u}      {}              2     12.50%
{4}      {M}             1      6.25%
{n}      {}              1      6.25%
{'}      {}              1      6.25%
{O}      {0}             1      6.25%
{}       {둥}             1      6.25%
{e}      {}              1      6.25%
{델}      {텔}             1      6.25%
The remaining but hidden errors make up 0.00%
