### ISSUE TITLE
Can't predict well with the EarlyStopping

### ISSUE THREAD

**Issue by xuyin666** [Calamari-OCR/calamari#143]
Hello, everyone ! I have an issue who has confused me very much. 
When I train a model with the code "calamari-train --files trainingSet/*.png",  after a night of training in local , I have a model who predicts well in my prediction set with the average sentence confidence about 80%. Because I don't use the Early Stopping, so calamari doesn't know when to stop training the model. Every time it's me who stop the training manually.
When i want to use the Early Stopping, I use the code "calamari-train --files trainingSet/*.png  --validation validationSet/*.png", I get a model in 20 minutes, But it predicts very badly. Its average sentence confidence in the prediction Set is 20%. 
It's the same bad result when i use the command "calamari-corss-fold-train"
Could anyone help me for the issue, please.
Also what's the meaning of the average sentence confidence?

**Comment by ChWick** [comment]
I think that the `--early_stopping_frequency` might be too low for your number of training instances. Try for example `--early_stopping_frequency 1000` or even 2000 to check for a new best model every 1000 (or 2000) iterations. Naturally, training will take longer then.

The average sentence confidence is the average probability of the softmax layer of each predicted character. This value can be seen as "confidence of the network about its prediction" but it is usually too high.

**Comment by xuyin666** [comment]
Thanks a lot !!! It solved my problems. It helps so much.
And could I ask for you another question, please ? 
I have used the TensorBoard for displaying how the loss decrease, it works very well with calamari. 

And I also want to display how the model behaves in the validationSet. But I met a problem.
I did the samething as the exemple of tensorboard.  
I have added a line of code `validation_data = val_dataset_gen` in the file tensorflow_backend in the self.model.fit just like this. 
`self.model.fit(
            dataset_gen,
            steps_per_epoch=steps_per_epoch,
            epochs=1000,
            use_multiprocessing=False,
            shuffle=False,
            verbose=0,
            validation_data = val_dataset_gen
            callbacks=[
                v_cb, es_cb, tensorboard_callback
            ]
        )`
But i have the error 
`File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 511, in call
    ctx=ctx)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Labels length is zero in batch 0
	 [[node model/ctc/CTCLoss (defined at /lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1751) ]] [Op:__inference_distributed_function_8778]

Function call stack:
distributed_function
2019-11-26 14:08:24.808484: W tensorflow/core/kernels/data/generator_dataset_op.cc:102] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]]
2019-11-26 14:08:24.818900: W tensorflow/core/kernels/data/generator_dataset_op.cc:102] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]]`

So could you tell me where the error is or if there are some another possibilities for displaying the  how the model behaves in the validationSet, please

My command used is `calamari-train --files ../TrainingSet1/*.png --batch_size 32 --checkpoint_frequency 0.5 --validation ../ValidationSet/*.png --early_stopping_frequency 1000`

Thanks a lot

**Comment by xuyin666** [comment]
@ChWick  👍

**Comment by srikanthsampathi** [comment]
how to finetune model/use existing model as base and improve accuracy

**Comment by ChWick** [comment]
@srikanthsampathi Use the `--weights model.ckpt.json` parameter. Some pretrained models can be found [here](https://github.com/Calamari-OCR/calamari_models) (And create a new issue if it is not directly related to an existing one)
