### ISSUE TITLE
Calamari vs 2019

### ISSUE THREAD

**Issue by mrocr** [Calamari-OCR/calamari#147]
@ChWick 
Thank you for your hard work, you are truly appreciated,

Lately, I have noticed that you started experimenting with various methods in-order to improve the recognition rate of arbitrary shaped text; such as handwriting.
Thus, I would ask: How does the Calamari perform, compared to the recent advancements in ocr?
such as:
- [Aster](https://github.com/ayumiymk/aster.pytorch)
- [MegReader](https://github.com/Megvii-CSG/MegReader): option of 2D-CTC & Attention Decoder
- [KISS](https://github.com/Bartzi/kiss)
- [MORAN v2](https://github.com/Canjie-Luo/MORAN_v2), [moran_v2_GPU](https://github.com/jiaying96/moran_v2_GPU)
- [Sequence-to-Sequence Domain Adaptation Network](http://openaccess.thecvf.com/content_CVPR_2019/papers/Zhang_Sequence-To-Sequence_Domain_Adaptation_Network_for_Robust_Text_Image_Recognition_CVPR_2019_paper.pdf)
- [deep-text-recognition-benchmark](https://github.com/clovaai/deep-text-recognition-benchmark)
- [Aggregation Cross-Entropy](https://github.com/summerlvsong/Aggregation-Cross-Entropy)

**Comment by deepseek** [comment]
@ChWick @chreul

**Comment by mrocr** [comment]
@ChWick @chreul

**Comment by chreul** [comment]
in order to answer that question one would have to perform extensive comparative evaluations, which isn't something we intend to invest any time in right now.
we plan to mainly focus on consolidation and usability for the foreseeable future. however, we are monitoring recent developments. thanks for the links :-)
