### ISSUE TITLE
migrating models from calamari 0.3.5 to 1.0.*

### ISSUE THREAD

**Issue by wosiu** [Calamari-OCR/calamari#149]
After upgrading calamari from 0.3.5 to 1.0.0 I get:
```
  File "/opt/anaconda2/envs/ocr_ws_dev/lib/python3.7/site-packages/calamari_ocr/ocr/checkpoint.py", line 81, in _single_upgrade
    "Due to a update to tensorflow 2.0, the weights can not be converted yet. A retraining is required.")
Exception: Due to a update to tensorflow 2.0, the weights can not be converted yet. A retraining is required.
```

Is there any serious reason to not auto_update old checkpoints? 
In my case it's quite crutial, because I've got quite a few models and I guess by `retraining` it means to train those models from a scratch?
It seems strange, because normally migration from tensorflow 1.15 to 2.0 for raw tensorflow models works just fine.

**Comment by chreul** [comment]
please see @ChWick 's explanation [here](https://github.com/Calamari-OCR/calamari_models/issues/4#issuecomment-610970725)
