### ISSUE TITLE
What version  of tensorflow and keras can use for using correctly calamari?

### ISSUE THREAD

**Issue by Tailor2019** [Calamari-OCR/calamari#151]
@ChWick 
Dear,
Please what version of Tensorflow and keras can use because when i use a version of Tensorflow>=1.12 i have this error 👍 
![image](https://user-images.githubusercontent.com/47376635/74251946-35b16600-4ced-11ea-8704-be1121bc6a05.png)

**Comment by Tailor2019** [comment]
@ChWick 
Dear,
I'm trying to Install calamari with anaconda but the same error occured.
I'm using:
Python 3.7
I install it from source using this instruction "python setup.py install"
my CPU is an old one that not support AVX instructions.
Please please help me to overcome this problem.

**Comment by ChWick** [comment]
The current version of Calamari requires tensorflow>=2.0. Unfortunately, the pip packages are required with AVX instructions enabled. I think your only option is to self-compile tensorflow for your platform (takes quite some time) or to search if someone else already built and shared a custom wheel (e.g., https://github.com/yaroslavvb/tensorflow-community-wheels/issues or https://github.com/yaroslavvb/tensorflow-community-wheels/issues/125)

**Comment by Tailor2019** [comment]
@ChWick 
thank you very much
