### ISSUE TITLE
Training Calamari on the IAM database

### ISSUE THREAD

**Issue by Tailor2019** [Calamari-OCR/calamari#158]

**Comment by Tailor2019** [comment]
Hi, 
@ChWick 
When i try to train calamari on the IAM it mentionned that it is required to generate the ground truth files for this datbase then launch the training.
When i try to find a toolkit in the net i have found LabeMe ,  GEDI Annotation Toolkit ... but these toolkits generate only the .xml of the image.
For this issue, Please how can i generate .gt.txt for each image of my data.
Thank you for your help

**Comment by ChWick** [comment]
Hi,
is the IAM dataset PageXML? Then you can directly load it. Else you either must write a custom converter or provide a custom dataset to calamari (similar to PageXML, AbbyyXML, ...)
Maybe you can attach a sample file.

**Comment by Tailor2019** [comment]
Thank you for you response.
@ChWick 
The IAM database is not a PageXML.
This screenshot shows the format of this data
![image](https://user-images.githubusercontent.com/47376635/76779722-17d39700-67ac-11ea-9cdd-c4a50e202490.png)
In my case i will train Calamari with /data/words. For all images supported by this folder there is a file "words.xml" used as a ground truth file the screenshot above below shows the content of this file: it contain the text transcripted in each image.
![image](https://user-images.githubusercontent.com/47376635/76780061-b65ff800-67ac-11ea-8dad-ca206a5521db.png)

my issue is how to use this file to generate the .gt.txt files or there is another way to train this database.
Thank you for your help

**Comment by ChWick** [comment]
This data format is (currently) not supported by Calamari. Therefore, you must write a converter. However, as far as I understand, the line images are already present which simplifies a manual conversion:
* For each line extract the words and write it into a .gt.txt file
* For example, if the line name is `a01-000u-00.png` create a `a01-000u-00.gt.txt` file containing the words: `A MOVE to stop Mr. Gaitskell from` (automatically parsed from `words.txt`)

**Comment by Tailor2019** [comment]
@ChWick 
Thanks a lot! 
this proposition solve my issue.
