### ISSUE TITLE
Sample of training files

### ISSUE THREAD

**Issue by vfbsilva** [Calamari-OCR/calamari#161]
Where  can I find some samples or tutorials about how to create the training files? I want to use calamari to recover data from ID cards as the attached image. Is it feasible? 
![sample](https://user-images.githubusercontent.com/874774/77658052-e8175280-6f54-11ea-8ff1-f872f14c7f1d.jpeg)

**Comment by ChWick** [comment]
Calamari is an ATR engine only. Its input is a text line that must be segmented in a previous step. Example files that can be used for training/prediction are located here: https://github.com/Calamari-OCR/calamari/tree/master/calamari_ocr/test/data
The most simple way is to use pairs of line images and text files.

**Comment by vfbsilva** [comment]
Does the background of input text has to be white?

**Comment by ChWick** [comment]
In all of our use-cases the background was white, but in general the color could be arbitrary. However, I expect that a significantly higher amount of GT is required.
Therefore, I recommend to binarize your input. Which should be straightforward on your ID cards: Grayscale -> Otsu should suffice.
