### ISSUE TITLE
 W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Cancelled: Operation was cancelled

### ISSUE THREAD

**Issue by vfbsilva** [Calamari-OCR/calamari#164]
What does it mean?

**Comment by andbue** [comment]
Nothing, I guess: https://github.com/tensorflow/tensorflow/issues/35100
I only get this warning when manually stopping the training process. If you experience further problems connected with this message, a more elaborate error report would be appreciated.

**Comment by stweil** [comment]
I get this message at the end of a [training](https://github.com/UB-Mannheim/AustrianNewspapers/wiki/Training-with-Calamari) last year and again today:
```
INFO     2023-04-26 19:53:12,419 calamari_ocr.ocr.training.trai: Training finished
2023-04-26 19:53:12.616129: W tensorflow/core/kernels/data/generator_dataset_op.cc:107] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
         [[{{node PyFunc}}]]
```

I used Python 3.9 with these packages (extract):
```
calamari-ocr==2.2.2
tensorflow==2.6.5
tensorflow-addons==0.17.1
tensorflow-estimator==2.6.0
```
