### ISSUE TITLE
Predicting Page-xml and saving as Page-xml

### ISSUE THREAD

**Issue by deepseek** [Calamari-OCR/calamari#168]
@ChWick @chreul @maxnth 

[example.zip](https://github.com/Calamari-OCR/calamari/files/4594088/example.zip)
 When having a page-xml that contains blank regions, example `textlines, words, illustration`.
I want to use Calamari to recognize only the `textline` or `word` regions, and then save the recognized text into the page-xml itself.
- Recognize selected region `-textlines` or `-words`
- Save recognized into the page-xml itself.

**Comment by chreul** [comment]
i am not sure if i understand the question...
what call do you want to perform and what output do you want to get? so predicting using --textlines should result in ocr text for all "TextLine" elements but their corresponding "Word" "TextEquivs" should remain empty (and vice-versa)? why?

**Comment by deepseek** [comment]
It might sound weird at first, but listen:
Some text detectors are only trained to output textlines, therefore i might only have page-xml files with textline regions `coordinates`, but with blank text.
Therefore, inputting those page-xml files into calamari>recognize each textline region> output page-xml files having the textline regions filled with the recognized text. `--textlines`

In the situation when both the lines and words are detected, an option of `--textlines --words` would do the trick.

Note: The lines and words are organized, so calamari only have to recognize the regions.
