### ISSUE TITLE
missing output data

### ISSUE THREAD

**Issue by usteiner9** [Calamari-OCR/calamari#170]
Hi, 
I ran tests wit the antiqua_modern model and the pred.txt is either empty or contains only one or two letters - anything I miss here?

Tanks
Uwe

**Comment by andbue** [comment]
Hi Uwe,
could you please append an image file?
Without any further information, I can only guess:

- your line image might be rotated
- you're trying to read whole pages without giving calamari any information about where to find lines (eg. by using PAGE XML layout description files)

**Comment by usteiner9** [comment]
![image](https://user-images.githubusercontent.com/1666491/81539255-45822a00-9370-11ea-9650-ca539023988e.png)
 here is the png

**Comment by andbue** [comment]
Quoting readme.md: "Currently only OCR on lines is supported." You could cut out lines using [ocropus](https://github.com/tmbarchive/ocropy/blob/master/ocropus-gpageseg) or [kraken](http://kraken.re/) segmenters or manually create a PAGE file containing line segments using [LAREX](https://github.com/OCR4all/LAREX) or [Aletheia](http://www.primaresearch.org/tools/Aletheia/)

**Comment by chreul** [comment]
exactly, the problem was that you used an entire page as input. please consider the links provided in https://github.com/Calamari-OCR/calamari/issues/169
