### ISSUE TITLE
Speed on low profile GPU.

### ISSUE THREAD

**Issue by PratapMehra** [Calamari-OCR/calamari#174]
I have installed a low profile NVIDIA GeForce GT 719 for testing. It takes 9.7 sec just for 20 lines. Surely I am missing out lot of things. It took lot of time to load CUDA driver.

As per documents It is much faster. Is it a fault of hardware?
I am mostly in .net and new to Python. Can anyone let me know how much fast and real-time it is on some low profile GPU.
Do I always need to add checkpoint on each call or it could be in preloaded state to save time?
Do it need to loading CUDA drivers on each call?

![CalamariPridict20Lines1Of2](https://user-images.githubusercontent.com/9975980/82738040-9facc300-9d52-11ea-922a-87b71dceb53a.PNG)
![CalamariPridict20Lines2Of2](https://user-images.githubusercontent.com/9975980/82738043-a1768680-9d52-11ea-9cd2-c6f4002eccb1.PNG)

**Comment by andbue** [comment]
I don't know if it's helpful for a comparison, but this is the prediction performance on a more recent but still low profile GeForce GTX 1050Ti (raw data, no preprocessing, so CPU is not relevant here):
```
Prediction: 100%|██████████| 33638/33638 [16:18<00:00, 34.39it/s]
Prediction of 1 models took 978.896181344986s
```
– but I don't think it's only your GPU's fault. Calamari requests memory on the GPU and fires up some threads in the background to do the preprocessing efficiently for a large amount of data, e.g. reading in whole collections of books.
If you want to keep the model loaded in the background and feed it some data every now and then, try instantiating a Predictor object and use the .predict_raw function.
