### ISSUE TITLE
VoterParams should be import from calamari_ocr.proto

### ISSUE THREAD

**Issue by junxnone** [Calamari-OCR/calamari#177]
https://github.com/Calamari-OCR/calamari/blob/715ebcdd8672c72c39a533a49f01d4eb1b36a760/calamari_ocr/scripts/experiment_eval.py#L4

**Comment by ChWick** [comment]
Calamari 2.0 reworked `experiment_eval.py`, which is now called `predict_and_eval.py`. This issue is closed.
