### ISSUE TITLE
How to enable and add augmentation

### ISSUE THREAD

**Issue by edwardpwtsoi** [Calamari-OCR/calamari#187]
Hi, I was wonder how to add customised augmentation into the calamari trainer. I saw the third party orcdeg functions and augmentater class but I am not quite sure how to add more augmentations with randomness. Could you please give some guideline on how to achieve that? Many thanks!

**Comment by andbue** [comment]
Hi, I've only used the SimpleDataAugmenter so far, but I guess you could either
- use the n_augmentations argument for calamari-train if you just want more augmentations or
- modify the function augment_single in the SimpleDataAugmenter if you want other augmentation techniques. Depending on your use case, it might be helpful to apply random rotation for example (cf. the line commented out [here](https://github.com/Calamari-OCR/calamari/blob/d43aa99df44a92ae9a78ca9e534eb2f25295befa/calamari_ocr/ocr/augmentation/data_augmenter.py#L63) and the readme of https://github.com/NVlabs/ocrodeg).

**Comment by edwardpwtsoi** [comment]
Thanks for your reply.

- Does the n_augmentation mean how many time the augment_single method is applied to a single datum?

https://github.com/Calamari-OCR/calamari/blob/2bf6db5707c1bf5a267073b171386159cbda0620/calamari_ocr/ocr/augmentation/data_augmenter.py#L19

- If I want to implement new augmentation, basically, the augment_single method is the one I need to implement, right?

Thank you again for your time and kindness.

**Comment by andbue** [comment]
> - Does the n_augmentation mean how many time the augment_single method is applied to a single datum?

The parameter is a bit confusing, it depends on whether it's >1 or <1. More explanation can be found [here](https://github.com/Calamari-OCR/calamari/blob/d43aa99df44a92ae9a78ca9e534eb2f25295befa/calamari_ocr/ocr/augmentation/dataaugmentationparams.py#L9):
> ABS: amount is the factor how often the dataset is augmented, e.g. 100 samples, amount == 2 => 200 augmented samples
>      in total 300 samples (=epoch size)
> PER: percentage is the probability to "chose" an augmented sample, e.g. 100 samples, percentage == 0.5 => 100
>      augmented samples, in total 200 samples (=epoch size). 100 / 200 = 0.5.
>      Or percentage == 0.75 => 300 augmented samplees, in total 400. 300 / 400 = 0.75



> - If I want to implement new augmentation, basically, the augment_single method is the one I need to implement, right?
Correct. Have a look at the SimpleDataAugmenter for an example.

> Does this line run at every batch? If my augment_single has randomness the output of the same datum would be different in every epoch?

I think it depends. When you preload the dataset, augmentation is run once at the start of the training. When you train on the fly (--train_data_on_the_fly), augmented training data is not kept in memory, so it does change while training. @ChWick correct me if I'm wrong!

**Comment by edwardpwtsoi** [comment]
Got it! Thank you so much @andbue and @ChWick.
