### ISSUE TITLE
Applying data processor Text Normalizer

### ISSUE THREAD

**Issue by abhikatoldtrafford** [Calamari-OCR/calamari#196]
@ChWick 
I have updated calamari-ocr version to 2.0.0 and now training takes ages to start. Previously, calamari used to compute codec and start. Now, calamari takes 2+ days to apply text normalization. I cant afford to wait 3 days for training to start. Can someone help?
![Capture](https://user-images.githubusercontent.com/11613662/105937538-cb1f4480-607b-11eb-918c-020345aacd81.JPG)

**Comment by ChWick** [comment]
Hi, thanks for sharing! We also noticed some random dead locks when training. Unfortunately, we were not able to track it down, yet. Luckily, starting the process a second time (almost) always worked.

I also notice that you have a big number of lines. The process might also run out of memory (Calamari 2.0 might need a bit more RAM). Can you check this? If this is the case you can try to use the `--training_data_on_the_fly` and `--validation_data_on_the_fly` flags, which loads the data while training and therefore requires much less memory. Still, the codec must be computed beforehand which is why the text files must be loaded once.

**Comment by abhikatoldtrafford** [comment]
@ChWick I am using --training_data_on_the_fly and --validation_data_on_the_fly flags. I will restart the training and let you know. As such, the training isnt stuck or anything but text normalizer takes 2+ days which is definitely a no-go. Will update soon.

**Comment by ChWick** [comment]
@abhikatoldtrafford Let me know if this works. As I said, I randomly observed a similar (maybe) same behavior, but as soon as I saw that the program was "stuck" (or maybe just very slow), I restarted, and the problem was gone.
You are absolutely right that this is a no-go...

**Comment by abhikatoldtrafford** [comment]
> @abhikatoldtrafford Let me know if this works. As I said, I randomly observed a similar (maybe) same behavior, but as soon as I saw that the program was "stuck" (or maybe just very slow), I restarted, and the problem was gone.
> You are absolutely right that this is a no-go...

![1](https://user-images.githubusercontent.com/11613662/105969785-a4c6cc80-60ae-11eb-8cfc-00042d7246ef.JPG)
restarted it, again it is showing the same estimated time! There was no step for text normalization in the previous version, or at least it didnt take this long. Lets see!

**Comment by ChWick** [comment]
`2 it/s` is way too slow... On my machine, I get about `200K it/s`... I assume that restarting did not help in your case.
Did you try, to train a model without cross-fold-train, i.e. running
```
calamari-train --num_threads 6 --batch_size 4 --network=cnn=64:3x3,pool=2x2,cnn=128:3x3,pool=2x2,lstm=300,dropout=0.02,learning_rate=.00001 --epochs 20 --checkpoint_frequency 20000 --files "./Images/*.png" --train_data_on_the_fly --validation_data_on_the_fly --output_dir "./trained_model" --weights "./trained_model/1.ckpt"
```
Maybe this has something to do with the `cross-fold-training`...

**Comment by abhikatoldtrafford** [comment]
@ChWick may be there is a bug in cross-fold-training, not sure. I am starting with calamari-train, lets see what happens. Will let you know soon.

**Comment by abhikatoldtrafford** [comment]
@ChWick Ok so there is a bug in cross-fold-training. calamari-train works like its supposed to. Thanks so much for your help. And, may be try fixing the cross-fold-train part too when you are free? 
![Capture](https://user-images.githubusercontent.com/11613662/105975593-23bf0380-60b5-11eb-993f-d58b83e65f03.JPG)

**Comment by ChWick** [comment]
@abhikatoldtrafford  Thanks testing! This looks fine (`--training_data_on_the_fly`, ... etc) might not be required anymore.
I hope to reproduce your bug in order to fix is asap.

**Comment by abhikatoldtrafford** [comment]
@ChWick see, the bug is cross fold training takes long time in applying textnormalizer. Lets see what happens.

**Comment by ChWick** [comment]
Unfortunately, I could not yet reproduce this bug reliably. Maybe also the usage of a GPU plays a role (the log states that you use one)

**Comment by ChWick** [comment]
@abhikatoldtrafford Oh, I also must inform you that by default calamari does not train on the GPU you must specify
`export CUDA_VISIBLE_DEVICES=0` (or any other id) before any call

**Comment by abhikatoldtrafford** [comment]
@ChWick thanks... shall I paste 'export CUDA_VISIBLE_DEVICES=0' on train.py?
