### ISSUE TITLE
saved model format and prediction code

### ISSUE THREAD

**Issue by abhikatoldtrafford** [Calamari-OCR/calamari#199]
Previously these things happened for models:
a) model.h5 and model.ckpt got dumped.
b) We used 'Predictor(checkpoint='model.ckpt') to load the model

now the saving part is weird
a)
![1](https://user-images.githubusercontent.com/11613662/106152816-de2d3400-61a3-11eb-9e5c-c32c62919ab0.JPG)

b) Cant find the ckpt to load and predict.

Please help @ChWick , I want to predict using python script (not calamari-predict). Also, where is ckpt.json?

**Comment by ChWick** [comment]
* a): The checkpoint you are seeing can be used to resume training not for prediction. In `trained_model` a `best_model.ckpt.json` and `best_model.ckpt.h5` should exist. This is the model you are looking for
* b): It might be that I have to adjust the non-command-line support. I will have a look at it on the weekend

**Comment by abhikatoldtrafford** [comment]
@ChWick this error shows up : 'AttributeError: 'Sample' object has no attribute 'sentence' when I do this with the latest model:
for file, image in zip(args.files, images):
            _, prediction, _ = list(predictor.predict_raw([image]))[0]
            print(file, prediction.sentence)

Error in printing prediction.sentence.

**Comment by andbue** [comment]
Have a look at how it's done in predict.py: https://github.com/Calamari-OCR/calamari/blob/d48dc51e6154dd118c73578b26a27a73173af7ec/calamari_ocr/scripts/predict.py#L112
According to https://github.com/Planet-AI-GmbH/tf2_aip_base/tree/master/tfaip/base/predict/predictorbase.py, predict raw should return a list of samples. In your case, that would mean something like this should work:
```python
s = list(predictor.predict_raw([image]))[0]
inputs, (result, prediction), meta = s.inputs, s.outputs, s.meta
sentence = prediction.sentence
```

**Comment by abhikatoldtrafford** [comment]
@andbue @ChWick thanks. It works.

for Predictor:
s = list(predictor.predict_raw([image]))[0]
inputs,prediction, meta = s.inputs, s.outputs, s.meta
sentence = prediction.sentence


for MultiPredictor:
s = list(predictor.predict_raw([image]))[0]
inputs,(results,prediction), meta = s.inputs, s.outputs, s.meta
sentence = prediction.sentence

**Comment by ChWick** [comment]
@abhikatoldtrafford @andbue Thanks for the code, I updated the [Wiki](https://github.com/Calamari-OCR/calamari/wiki/Predicting-(Python-API))
