### ISSUE TITLE
prediction.avg_char_probability always returns 0

### ISSUE THREAD

**Issue by gdabhishek** [Calamari-OCR/calamari#202]
Hi @ChWick, 

print(prediction.avg_char_probability)  always returns 0, I guess avg_char_probability was not calculated properly.

So I am using the old code to calculate the avg_char_probability 

```python
avg_char_probability = 0
for p in prediction.positions:
       if len(p.chars) > 0:
                avg_char_probability += p.chars[0].probability
avg_char_probability /= len(prediction.positions) if len(prediction.positions) > 0 else 1
```

**Comment by andbue** [comment]
Thanks for reporting this!
The calculation of the char probability is now in Voter, which is only used in MultiPredictor. Maybe we should integrate MultiPredictor in Predictor so that Predictor actually is a MultiPredictor with only one checkpoint and a minimal Voter?

**Comment by ChWick** [comment]
@gdabhishek I can not confirm this. Can you provide more information about what you did?

**Comment by ChWick** [comment]
@gdabhishek I should have read @andbue 's message. This will be fixed with a pending commit.
