### ISSUE TITLE
Inference Time Optimization & Multithreading for Prediction 

### ISSUE THREAD

**Issue by gdabhishek** [Calamari-OCR/calamari#203]
Hi @ChWick/@andbue , 

Thank you for your great work, the results are awesome.

Can you please suggest any optimization technique to improve the model inference time?

I have tried few techniques but didn't worked..

**Comment by ChWick** [comment]
@andbue is currently working in speeding up the data processing pipeline using [opencv](https://github.com/Calamari-OCR/calamari/tree/opencv). You can try it, but it is not stable.
Futhermore, you can increase the `--batch_size` and use more threads.
Naturally, launching more than one prediction processes on partitioned data will yield the maximum gain.

**Comment by gdabhishek** [comment]
Hi @ChWick / @andbue,

I have used --num_threads 8 it was working for training the model, but it didn't work for prediction. So is there any way to implement multithreading for prediction. 

Thanks.

**Comment by chreul** [comment]
-j / --processes (should be renamed...)
also try increasing the batch size

**Comment by gdabhishek** [comment]
Thanks @chreul  it works.
