### ISSUE TITLE
Limit in number of input samples

### ISSUE THREAD

**Issue by nacho-pancho** [Calamari-OCR/calamari#218]
The method for specifying training files from the command line using wildcards is not suited to large training corpuses. (In my case I have millions of samples). This is a very easy thing to fix, by letting the input be specified using a txt file whose contents is the list of input files, one per line).

**Comment by andbue** [comment]
Wildcards can be expanded internally if you prevent your shell from expanding them first. See [https://github.com/Calamari-OCR/calamari/issues/12](https://github.com/Calamari-OCR/calamari/issues/12).

**Comment by nacho-pancho** [comment]
Thank you. Nevertheless, for many people (like me), using wildcards is too cumbersome. Why not adding a listfile option?

**Comment by ChWick** [comment]
Indeed, such an option could be helpful for some users. Currently, passing a `.json` to specify all parameters (including the files) is supported. (`--files config.json` and no other parameter)

**Comment by nacho-pancho** [comment]
I'll tell you my case, so you can see what kinds of things this would solve.
I have a large directory tree of several million images organized in subtrees for relevant reasons.
The way I do all other steps in my pipeline is to pass a simple txt file where I specify the full path (or relative) of each file. 
This not only serves one to specify all the dataset, but also to specify subsets, e.g., for cross validation or testing, or whatever reason. 
JSONs are OK, but it is way more simple to generate text files, which I can do with a single command line command in most any operating system.
