### ISSUE TITLE
Error when importing TextProcessor, TextProcessorParams

### ISSUE THREAD

**Issue by Tailor2019** [Calamari-OCR/calamari#219]
Hello!
@ChWick 
I'm using colaboratory to execute this code
1-I create a calamari_venv and I activate it .
2-I install Calamari with this command "!pip install calamari_ocr" 
when I try this """from calamari_ocr.ocr.text_processing import TextProcessor, TextProcessorParams
"""
it returns this error 
"""ModuleNotFoundError: No module named 'calamari_ocr.ocr.text_processing'"""
Six months a go  approximately   this code turned well without any error.
This problem It is about of calamari or what 
thanks in advance!

**Comment by ChWick** [comment]
Your code is probably still using the Calamari1.0 interfaces (Current version is Calamari2.x). To install an older version run `!pip install calamari_ocr<2.0.0`
