### ISSUE TITLE
Add convolution layers in order to ameliorate the accuracy of recognition

### ISSUE THREAD

**Issue by Tailor2019** [Calamari-OCR/calamari#220]
Hello!
@ChWick 
I using the 1.0 version of Calamari and when I trained it on Handwritten texts it don't give me the result I hope.
As a solution I try to add (+ convolution layers)
in  ""calamari/calamari_ocr/proto/calamari.proto ""(version 1.0 of calamari)
I put this modification
message LayerParams {
    enum Type {
        CONVOLUTIONAL = 3;
        MAX_POOLING = 4;
        LSTM = 2;
    }

    enum LSTMDirection {
        BIDIRECTIONAL_LSTM = 0;
    }

 is this possible to do this or it is better to migrate to the newest version of calamari?
Thanks in advance!

**Comment by ChWick** [comment]
To change the network architecture, you do not have to modify the code of calamari. Just use the command line arg:
```
--network=cnn=40:3x3,pool=2x2,cnn=60:3x3,pool=2x2,lstm=200,dropout=0.5

**Comment by Tailor2019** [comment]
Thanks so much for your continuous help !!!
