### ISSUE TITLE
Wiki instructions for PageXML training are wrong

### ISSUE THREAD

**Issue by Baciccin** [Calamari-OCR/calamari#222]
I noticed an issue with the instructions on how to train using PageXML data here: https://github.com/Calamari-OCR/calamari/wiki/Dataset-formats#page-xml-files

I found that if specifying the `--text_files` flag, as described in the first paragraph, attempting to train Calamari will fail with `ValueError: Training dataset is empty`. Omitting it (like in the  training tests in `gitlab-ci.yml`) fixes the issue.

**Comment by ChWick** [comment]
Thanks for the information! This should be fixed in the new docs at https://calamari-ocr.readthedocs.io/en/latest/doc.dataset-formats.html#pagexml
