### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by Alexd134** [Calamari-OCR/calamari#223]
When running the code to predict my image I receive this error
![image](https://user-images.githubusercontent.com/32267026/114319015-8302b080-9b07-11eb-9335-5c24c8bae170.png)

**Comment by ChWick** [comment]
This seems to be an issue with tensorflow and a "too new" hdf5 version (see e.g. [here](https://github.com/keras-team/keras/issues/14265) ). Try to downgrade: 
```
pip install 'h5py<3.0.0'
```

**Comment by bertsky** [comment]
Why did you close this already @ChWick? The current h5py is 3, thus installation will not work out of the box

https://github.com/Calamari-OCR/calamari/blob/62fd621b28ea772d2c64521db86438948a30dce0/requirements.txt#L3

I think the above fix should be in the requirements.txt.

Related: #179

**Comment by bertsky** [comment]
Should also be backported to the 1.0 branch (and release) I think. (I know keeping up with TF's many nuissances is a PITA ... just trying to improve the UX for Calamari.)
