### ISSUE TITLE
using a GPU: dependencies

### ISSUE THREAD

**Issue by uvius** [Calamari-OCR/calamari#226]
The conda installation command 
```
conda env create -f environment_master_gpu.yml
```
refers to a non-existing file `environment_master_gpu.yml`.
However, there is only a file `environment_master.yml`.

To make use of my GPU, I installed the latest cudatoolkit and cudnn 11.2, but it turns out that Calamari needs libcuda-10.1 instead. Could you make this dependency explicit and ideally include it in the conda installation example? Maybe by providing the missing file.

**Comment by ChWick** [comment]
The version of CUDA depends on the Tensorflow version (currently 2.4.x). I'll check if using the `cudatoolkit` in the envirnoment is a solution.
