### ISSUE TITLE
how to predict images

### ISSUE THREAD

**Issue by aaferrero** [Calamari-OCR/calamari#237]
the docs says the way of predcit is ’predictor.predict_raw(raw_image_generator)’， I search for a lot of time and still dont know how to struct raw_image_generator，the way of feed to ‘predict_raw’.

**Comment by ChWick** [comment]
Thanks for pointing this out. I improved the docs:

Whereby a `raw_image_generator` is of type `Iterable[np.ndarray]` for example a list of images:
```
raw_image_generator = [np.zeros(shape=(200, 50))]
```
