### ISSUE TITLE
dataset name in HDF5 is really 'transcripts', not 'transcriptions'

### ISSUE THREAD

**Issue by nacho-pancho** [Calamari-OCR/calamari#243]
Hi,
I believe there is a small error in the Wiki.

The Wiki says the dataset for transcripts (in my case, I have them) should be 'transcriptions'.
However, everywhere in the code, and in particular in:

calamari_ocr/ocr/dataset/datareader/hdf5/reader.py
calamari_ocr/ocr/dataset/datareader/hdf5/hdf5_dataset_writer.py

The name is really 'transcripts'.

**Comment by andbue** [comment]
Thanks, I changed it in the Wiki and the docs!
