### ISSUE TITLE
training Calamari starting from existing model

### ISSUE THREAD

**Issue by nacho-pancho** [Calamari-OCR/calamari#245]
Hi all,
I need to train a Calamari model starting from an existing checkpoint, but using a different dataset. 
I haven't figured out how to do this with the scripts that are shipped with Calamari. 
Specifically:
- The calamari-train script does not allow me to load an existing model.
- The calamari-resume-training script allows me to resume training from a checkpoint; however, apparently,  the training data is already bundled within the checkpoint.
I need something that can take the current state of the network and *new* training/validation  datasets to further train the network.
Is there a way to do this?
Thank you for your great work!

**Comment by andbue** [comment]
You can use the --weights parameter in calamari-train and calamari-cross-fold-train in Calamari 2.0 or --warmstart.model with calamari-train in Calamari 2.1. Cross-fold-train in 2.1 still uses --weights – there are some inconsistencies in the new CLI that need some polishing.

**Comment by nacho-pancho** [comment]
> You can use the --weights parameter in calamari-train and calamari-cross-fold-train in Calamari 2.0 or --warmstart.model with calamari-train in Calamari 2.1. Cross-fold-train in 2.1 still uses --weights – there are some inconsistencies in the new CLI that need some polishing.

Thank you very much for your quick response! I guess the largest file within a checkpoint would be the weights file right? "variables"

**Comment by andbue** [comment]
The .ckpt.h5 is the keras model in h5 format, the .ckpt.json contains the metadata of the model, e.g. the codec and pre-/postprocessing options.
