### ISSUE TITLE
use calamari-predict-and-eval or calamari-eval on PageXML

### ISSUE THREAD

**Issue by alexander-winkler** [Calamari-OCR/calamari#248]
Hallo!

I was wondering if there is a way to run 'calamari-eval` or `calamari-predict-and-eval` on PageXML files as well. I couldn't find anything in the documentation and/or in the help pages (v2.1.1).

 `calamari-predict-and-eval --help` results in a `paiargparse.dataclass_parser.RequiredArgumentError: The following arguments are required: --checkpoint` error, btw, after outputting the version number – same behaviour with other commands as well `tfaip.util.logging: Uncaught exception`)

Thank you!

**Comment by andbue** [comment]
Hi, I've called for some docstrings and --help in #238 already. For a working example of predict-and-eval on PageXML, have a look at the Colab Notebook: https://github.com/andbue/calamari_demo/blob/main/calamari_train.ipynb.

**Comment by alexander-winkler** [comment]
The Colab Notebook looks unbelievably helpful, thank you very much! I wish I had found this earlier!

So, as of now, the `calamari-predict-and-eval` behaviour that work for me in `v2.1.1` is

## Line snippets

```bash
calamari-predict-and-eval --checkpoint "/path/to/models/*.ckpt" --data.images "path/to/snippets/*.png" --data.texts "path/to/gt/*.gt.txt" -skip_empty_gt True
```

## PageXML

```bash
calamari-predict-and-eval --checkpoint  "/path/to/models/*.ckpt.json --data "PageXML" --data.images "path/to/pageimages/*.bin.png --skip_empty_gt True
```

Thanks!
