### ISSUE TITLE
Wrong glyph positions in json output

### ISSUE THREAD

**Issue by opaetzel** [Calamari-OCR/calamari#250]
I tried getting the positions for individual glyphs by exporting json with `calamari-predict` and the command line switch `--extended_prediction_data True`. 
When checking the global_start or local_start positions, they don't match up with the characters in the input image. 

calamari-ocr version is 2.1.1 from pip and I used the gt4histocr model 0 from the models repository. The input and output files are attached. 

![00000014_line_00000007](https://user-images.githubusercontent.com/12102742/119383857-2bd62b00-bcc4-11eb-9a6d-cbd753abfda5.png)
[00000014_line_00000007.json.txt](https://github.com/Calamari-OCR/calamari/files/6533920/00000014_line_00000007.json.txt)

**Comment by ChWick** [comment]
Thanks for pointing this out! Will be fixed in 2.1.2 (or current master)
