### ISSUE TITLE
I want to train a mixed model of English+Arabic. How should I choose the '--bidi_dir' parameter?

### ISSUE THREAD

**Issue by Lier007** [Calamari-OCR/calamari#254]

**Comment by andbue** [comment]
It depends. If your lines are either Arabic or English, the default "auto" should work. If you've got mixed LTR and RTL in lines, "auto" guesses the paragraph direction based on the characters in the text. The parameter sets the base direction or paragraph direction, which is only helpful if you know that all your lines have to be read either starting from the left or starting from the right.

In calamari >2.1, the parameters are "--data.pre_proc.processors.2.bidi_direction" for the preprocessing and  "--data.post_proc.processors.2.bidi_direction" for the postprocessing.

**Comment by Lier007** [comment]
Thank you very much, ’auto‘ works.
