### ISSUE TITLE
WARNING:tensorflow:No training configuration found in the save file, so the model was *not* compiled. Compile it manually.

### ISSUE THREAD

**Issue by Dhanachandra** [Calamari-OCR/calamari#256]
How to solve this error? May be because of this I got print(prediction.sentence) as nothing. 

```python
from calamari_ocr.ocr.predict.predictor import Predictor, PredictorParams
predictor = Predictor.from_checkpoint(
    params = PredictorParams(),
    checkpoint = '/home/ubuntu/data/ML-DL/Rahul/table_detection/all_data/dhana/OCR_softwares/CALIMARI/calamari_models/uw3-modern-english/4.ckpt',
)
img = cv2.imread('/home/ubuntu/data/ML-DL/Rahul/table_detection/all_data/image/9739/images/10.png')
for sample in predictor.predict_raw([img]):
    inputs, prediction, meta = sample.inputs, sample.outputs, sample.meta

print(prediction.sentence)
```

**Comment by ChWick** [comment]
This is a warning that can be ignored.

Can you share your image to example why you receive an empty prediction?

**Comment by Dhanachandra** [comment]
![10](https://user-images.githubusercontent.com/10828657/120625030-e8777b80-c47e-11eb-883c-6c6644c6b5e3.png)

This is the image.

**Comment by ChWick** [comment]
Thanks, Calamari is a line based OCR, not a full OCR software for documents, i.e. you need to  split you image into text lines first, then apply Calamari.
Use for example [OCRopy](https://github.com/ocropus/ocropy):
* `./ocropus-nlbin your_image.png -o page`
* `./ocropus-gpageseg 'page/????.bin.png'`

This will output lines in `page`

**Comment by Dhanachandra** [comment]
Okay thanks for the information.
