### ISSUE TITLE
Error in `calamari-predict` when no `--output_dir` provided

### ISSUE THREAD

**Issue by alexander-winkler** [Calamari-OCR/calamari#257]
When running `calamari-predict` (`v2.1.2`) with the `--extended_prediction_data True` parameter the default `output_dir` (`None` according to the [docs](https://calamari-ocr.readthedocs.io/en/latest/doc.command-line-usage.html#calamari-predict)) causes a `FileNotFountError`:

```
Traceback (most recent call last):
  File "/home/user/virtualenvs/calamari_pypi/bin/calamari-predict", line 8, in <module>
    sys.exit(main())
  File "/home/user/virtualenvs/calamari_pypi/lib/python3.8/site-packages/calamari_ocr/scripts/predict.py", line 188, in main
    run(args.root)
  File "/home/user/virtualenvs/calamari_pypi/lib/python3.8/site-packages/calamari_ocr/scripts/predict.py", line 155, in run
    os.mkdir(output_dir)
FileNotFoundError: [Errno 2] No such file or directory: ''
```

You have to explicitly provide an `--output-dir`

**Comment by ChWick** [comment]
I have difficulties to reproduce the error, can you provide me your call? Thanks!

**Comment by alexander-winkler** [comment]
The call was just something like 

```
calamari-predict --data PageXML --data.text_index 1 --data.images "image.jpg" --data.xml_files "image.xml" --checkpoint "model.ckpt.json" --extended_prediction_data True

```

**Comment by ChWick** [comment]
Thanks! Unfortunately, I still cant reproduce the error using the current master (maybe it was already fixed?). Please reopen, if you can share the exact command, version, and maybe also the "files".
