### ISSUE TITLE
Same result of evaluation with the  1.0 version and the 2.1.1 version of Calamari on arabic database 

### ISSUE THREAD

**Issue by Tailor2019** [Calamari-OCR/calamari#258]
Hello!
@ChWick 
when I used the 1.0 version of calamari the evaluation command give me this result:
```
Got mean normalized label error rate of 100.00% (87988 errs, 87991 total chars, 88020 sync errs)
GT       PRED     COUNT    PERCENT   
{ال هحور هب يجنملا لمعلا يف دهتجم هرخآلا بلاط كلذكو} {}              1      0.06%
{لب . ةقيوازتل حفصتلا هتياغ نوكت الأ اذه انباتك يف رظانلل يغبني دقو} {}              1      0.07%
{جزتمت ،لبجلا ةيدوأ يفو ،لبجلا فورج ىلع دباعملا رشتنت .ةعئارلا ءاقرزلا ءامسلاب} {}              1      0.09%
{نأ نودقتعي مهف ،رخآ يأر مهل اهءانيأ نأ ريغ ،يذوبلا وابيشت دبعم} {}              1      0.07%
{اديدحتو ،لعفلاب ةعبس زونك نم اهمسا تذخأ زونك ةعبسلا ةدلبلا هذه} {}              1      0.07%
{ةيبرعلا ىلإ اهتمجرت نكمي ىاليف لاثمت يه} {}              1      0.04%
{ةيقافتا فدهت ، رحصتلا نم ةبرتلاو يضارألا ةيامح ىلإ ةفاضإلابو} {}              1      0.07%
{ةمدقتملا نادلبلا مزتلتو . رقفلا ةبراحم ىلإ ًاضيأ رحصتلا ةحفاكم} {}              1      0.07%
{نع ةرثأتملا نادلبلا دوهج معدب ، ةيقافتإلا هذه بجومب ، ومنلا} {}              1      0.07%
{نواعتلا راطإ يف ةيفاكلا ةينقتلاو ةيلاملا ةدعاسملا اهحنم قيرط} {}              1      0.07%
The remaining but hidden errors make up 99.32%
```
the same result  approximately when I use the latest  there is only a variation of 
`Average sentence confidence: 99.94%`
I'm using this command for prediction :

```
!calamari-predict  --checkpoint '/directionof best model obtained after pretraining of arabic model 3/best.ckpt'  --output_dir '/directiontooutputdir' --data.images '*.png' 
```

I'm using this command for evaluation

```
!calamari-eval --gt.texts *.gt.txt 
```

But the result is unexpected

```
Evaluation: 100% 1424/1424 [00:00<00:00, 7077.97it/s]
Evaluation result
=================
Got mean normalized label error rate of 100.00% (88180 errs, 88183 total chars, 88212 sync errs)
GT       PRED     COUNT    PERCENT   
{هئامثالث نم رثكأ اوهويج لبج يف دباعملا ددع ناك ، هراهدزا تارتف رثكأ يف} {}              1      0.08%
{. ةيبيللا ةيبعشلا ريباعتلاب} {}              1      0.03%
{ةميدق ةيباتك صوصن ،فسألا عم انيدل تسيلو . نينسلا تائمب داليملا لبق اهتنكس} {}              1      0.08%
{يتاللاو ندملا يف نلمع يتاللا تايفيرلا نيب حضاو فالتخا دوجو نع} {}              1      0.07%
{ريغي نا دب ال ـضفحلاب نامزلا بعالنو نايسنلا تافآ نأو اليوط ادما} {}              1      0.07%
{بتك يف نودملا نيعملا اذه يف وه ثراحلا نب رضنلا'' هملعت يذلا صصقلا نيعم نوكي نأ دب الو} {}              1      0.10%
{كلاذ لاثماو ''ةعلقلا رادب ةتعم مه ،رجه ونب نارهش لويق ،ام هونبو ،ام هوخا ،ام حرش'' :ةصن اذهو ،ناويخ دجسم يف رجح} {}              1      0.13%
{و مسرلا نفل ةرودو ةينيصلا ةمجرتلل تارود ةماقإو ةينيصلا} {}              1      0.06%
{.هيعامتجإلا لئاضفلا نم راثيإو هفعو ةنامأو ءافوو قدص ىف عمتجملل} {}              1      0.07%
{. هيداصتقالا ةيمنتلا هجاوت يتلا تايدحتلاو ةئشانلا تالكشملا ةهجاوم يف مهلامعأ ريوطتل ةيملعلا ةيمنتلا ةيرظن} {}              1      0.12%
The remaining but hidden errors make up 99.19%
INFO     2021-06-03 10:59:45,068 calamari_ocr.ocr.dataset.datar: Resolving input files
```

I'm using for the prediction the ""test""part of my database
Please how can I resolve this problem?
thanks so much for continuous help

**Comment by ChWick** [comment]
You specified a custom output directory for `calamari-predict`: `--output_dir '/directiontooutputdir' `, therefore by default `calamari-eval` does not find any prediction file `.pred.txt`, You must either manually specify the prediction texts during `calamari-eval` (use `--pred.texts /directiontooutputdir/*.pred.txt`) or omit the `--output_dir` parameter completely.

**Comment by Tailor2019** [comment]
Thanks a lot!!

**Comment by Tailor2019** [comment]
Hello!
@ChWick 
this option does not exist ""--pred.texts"" it returns me this error 
`CRITICAL 2021-06-05 09:27:57,262             tfaip.util.logging: Uncaught exception
Traceback (most recent call last):
  File "/usr/local/bin/calamari-eval", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.7/dist-packages/calamari_ocr/scripts/eval.py", line 157, in run
    main(parse_args())
  File "/usr/local/lib/python3.7/dist-packages/calamari_ocr/scripts/eval.py", line 163, in parse_args
    return parser.parse_args(args=args).root
  File "/usr/local/lib/python3.7/dist-packages/paiargparse/main_parser.py", line 94, in parse_args
    raise UnknownArgumentError(f"Unknown Arguments {' '.join(argv)}. Possible alternatives:{''.join(help_str)}")
paiargparse.dataclass_parser.UnknownArgumentError: Unknown Arguments --pred.text
	--pred.texts. Alternative: --gt.texts
`

**Comment by ChWick** [comment]
Sorry, you must additionally specify: `--pred File`

**Comment by Tailor2019** [comment]
@ChWick 
I'm using 
!calamari-eval --gt.texts *.gt.txt   --pred '/direction to pred.txt files/*.pred.txt'
this is the error returned 
`CRITICAL 2021-06-05 10:42:12,707             tfaip.util.logging: Uncaught exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/paiargparse/dataclass_parser.py", line 210, in add_dataclass_field
    module, class_name = values.split(":")
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/calamari-eval", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.7/dist-packages/calamari_ocr/scripts/eval.py", line 157, in run
    main(parse_args())
  File "/usr/local/lib/python3.7/dist-packages/calamari_ocr/scripts/eval.py", line 163, in parse_args
    return parser.parse_args(args=args).root
  File "/usr/local/lib/python3.7/dist-packages/paiargparse/main_parser.py", line 89, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/local/lib/python3.7/dist-packages/paiargparse/main_parser.py", line 60, in parse_known_args
    namespace, args = self._data_class_parser.parse_known_args(args, namespace)
  File "/usr/local/lib/python3.7/dist-packages/paiargparse/dataclass_parser.py", line 536, in parse_known_args
    namespace, args = super(PAIDataClassArgumentParser, self).parse_known_args(args, namespace)
  File "/usr/lib/python3.7/argparse.py", line 1796, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.7/argparse.py", line 2002, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.7/argparse.py", line 1942, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.7/argparse.py", line 1870, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/local/lib/python3.7/dist-packages/paiargparse/dataclass_parser.py", line 480, in __call__
    add_dataclass_field(parser, pai_node, prefix, root, values, arg_field=arg_field, ignore=ignore)
  File "/usr/local/lib/python3.7/dist-packages/paiargparse/dataclass_parser.py", line 214, in add_dataclass_field
    f"Invalid module and class name {values}. Must be 'path.to.module:class_name' or in {list(choices.keys())}")
ValueError: Invalid module and class name /content/drive/MyDrive/calamari2.1.1testmodel3/Test-Akhbar1000.pred.txt. Must be 'path.to.module:class_name' or in ['FileDataParams', 'File', 'PageXML', 'Abbyy', 'Hdf5']
`

**Comment by ChWick** [comment]
I mean "additional":
```
calamari-eval --gt.texts .gt.txt --pred File --pred.texts '/direction to pred.txt files/.pred.txt'
```

**Comment by Tailor2019** [comment]
it  works thanks so much !

**Comment by ChWick** [comment]
@Tailor2019 Thats great!
