### ISSUE TITLE
Check input width and height before training 

### ISSUE THREAD

**Issue by a41888936** [Calamari-OCR/calamari#26]
I try to combine OCR whole process (Text Detection -> pre-processing Image -> Text Recognition)

To make pre-processing, I want to make sure Input size of Text Recognition(Calamari) model

I checked that calamari normalized height(default=48) and width(resized height-proportional )

So input sizes are not fixed. am I right?

What I wonder is if all input size are not fixed, How model is working...

**Comment by a41888936** [comment]
@chreul 
Sorry for lack of my English and  knowledge in this fields. 

So I want you to ask again what I understood. You mean that input size before going to the model is fixed? And that input size is model specific.  Am I right? 

where can I find that logic in code? 

I tried to find that logic in calamari,  but I don't know where it is

**Comment by chreul** [comment]
Have also look at scale_to_h in 
https://github.com/Calamari-OCR/calamari/blob/master/calamari_ocr/ocr/data_processing/center_normalizer.py

**Comment by a41888936** [comment]
https://github.com/Calamari-OCR/calamari/blob/master/calamari_ocr/scripts/apply_data_preprocessing.py

I guess It is the script that I can check the input.

I run the script the data in "/calamari/calamari_ocr/test/data/uw3_50lines/train"

origin image
1.
![010001 bin](https://user-images.githubusercontent.com/24805731/46849634-69dff280-ce2b-11e8-8980-c248e901ec0c.png)
(1421 X 54)
2.
![010002 bin](https://user-images.githubusercontent.com/24805731/46849641-77957800-ce2b-11e8-8dca-d89bdde09c3c.png)
(186 X 44)

normalized image
1.
![010001 bin](https://user-images.githubusercontent.com/24805731/46849693-ad3a6100-ce2b-11e8-9240-1f49559f7858.png)
(1065 X 48)
2.
![010002 bin](https://user-images.githubusercontent.com/24805731/46849705-baefe680-ce2b-11e8-9473-73660bac3003.png)
(171 X 48)

I think  input data's size(width*height) is should be the same but It's not

am I misunderstanding something?

**Comment by ChWick** [comment]
The center normalizer (part of the data preprocessing) adds padding to the top and bottom of a line (depending on the warping) before rescaling it to the desired height, thus the ration width/height changes.
