### ISSUE TITLE
How can I learn the result of the evaluation command?

### ISSUE THREAD

**Issue by Tailor2019** [Calamari-OCR/calamari#261]
Hello!
@ChWick 
How can I read this line of the result from calamari-eval command 
```
GT FILE                                                      LEN  ERR SER CONFUSIONS
Test-Akhbar108                                                 62   5   5 {("'ـه", 'م'): 1, ('أ', 'ن'): 1, ("'", ''): 1
```
Thanks a  lot !

**Comment by ChWick** [comment]
This particular line means:
* Filename `Test-Akhbar108`
* Number of Characters in the line (GT): 62
* Number of errors in the Prediction: 5 (so the CER is 5/62)
* Number of sequence errors (usually the same as ERR, just ignore it)
* Confusions are the "errors" of the line: e.g. in the GT there was the first character (or empty) but the networked predicted the second element of the tuple.. The number after the tupled inducates how often this error occurred.
