### ISSUE TITLE
Key cnn_lstm/B not found in checkpoint

### ISSUE THREAD

**Issue by chreul** [Calamari-OCR/calamari#27]
self._traceback = tf_stack.extract_stack()

NotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key cnn_lstm/B not found in checkpoint
	 [[{{node save_1/RestoreV2}} = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_1/Const_0_0, save_1/RestoreV2/tensor_names, save_1/RestoreV2/shape_and_slices)]]

how can I solve this problem?

_Originally posted by @hsl20130659 in https://github.com/Calamari-OCR/calamari/issues/11#issuecomment-429750027_

**Comment by chreul** [comment]
please perform a dry run (--dry_run) and post (part of) the output.

**Comment by stweil** [comment]
It looks like the model needs an upgrade as described [here](https://github.com/Calamari-OCR/calamari#upgrading-of-old-models). I get a similar error `Key B not found in checkpoint`, but the instructions refer to a script `calamari_ocr/scripts/tensorflow_rename_variables.py` which is not part of the code.
