### ISSUE TITLE
ValueError exception caused by bad GT from Transkribus PAGE XML export

### ISSUE THREAD

**Issue by stweil** [Calamari-OCR/calamari#299]
Training of a Fraktur model with Transkribus generated PAGE XML ground truth data from UB Tübingen causes a fatal exception `ValueError: zero-size array to reduction operation maximum which has no identity` right at the beginning of the training process while loading samples.

The problem could be reduced to a single PAGE XML file (see [details](https://github.com/UB-Mannheim/gt-fraktur/wiki#training-process)). That file includes a [baseline with only a single point](https://github.com/ubtue/gt-fraktur/blob/81b065f88f4dc491f21835f9fa0ee72a681bac8f/zpk_1838_01/zpk_1838_01/page/zpk_1838_01_0033.xml#L214).

The following minimized PAGE XML is sufficient to reproduce the issue:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<PcGts xmlns="http://schema.primaresearch.org/PAGE/gts/pagecontent/2013-07-15" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://schema.primaresearch.org/PAGE/gts/pagecontent/2013-07-15 http://schema.primaresearch.org/PAGE/gts/pagecontent/2013-07-15/pagecontent.xsd">
    <Page imageFilename="zpk_1838_01_0033.tif" imageWidth="2405" imageHeight="2854">
        <TextRegion orientation="0.0" id="TextRegion_1620802933506_1168" custom="readingOrder {index:1;}">
            <Coords points="318,233 1322,233 1322,2535 318,2535"/>
            <TextLine id="line_1620802933615_1171" custom="readingOrder {index:25;}">
                <Coords points=""/>
                <Baseline points="1322,1572"/>
                <TextEquiv>
                    <Unicode>was er von uns fordert, hat Chriſtus ſelbſt uns an⸗</Unicode>
                </TextEquiv>
            </TextLine>
        </TextRegion>
    </Page>
</PcGts>
```

Transkribus PAGE XML is known for several issues, but used very often. So instead of raising a fatal expection such problems might better be reported and ignored.

**Comment by andbue** [comment]
Thanks! Should be fixed with [PR ](https://github.com/Calamari-OCR/calamari/pull/300)

**Comment by stweil** [comment]
I tested now with the latest code from Git master and can confirm that the training no longer crashes. Thank you for the fix!
