### ISSUE TITLE
Syntax error with latest release

### ISSUE THREAD

**Issue by stweil** [Calamari-OCR/calamari#30]
Running `calamari-predict` results in a syntax error:

    [...]
      File "/usr/local/lib/python3.5/dist-packages/calamari_ocr-0.2.0-py3.5.egg/calamari_ocr/ocr/datasets/abbyy_dataset/reader.py", line 127
        block: Block = Block(type, name, XMLReader.parseRect(blockNode, required=False))
             ^
    SyntaxError: invalid syntax

I tried both the Pip installation with virtual environment and an installation from latest Git sources. Both show the same error.

**Comment by stweil** [comment]
The error happens with Python 3.5 (Debian stable). It works with Python 3.6 (Debian unstable).

**Comment by stweil** [comment]
With `pip3 install calamari_ocr==0.1.8` I get a working installation for Python 3.5.
The default `pip3 install calamari_ocr` installs release 0.2.0 which does not work with Python 3.5.

**Comment by ChWick** [comment]
The current dev branch (commit 0bd3a88) removed all type hints that were not supported in python 3.5 yet. Thus, you can clone the dev branch (and optionally install it) to get a running version of calamari that supports python 3.5 and the current models of the models repository.
