### ISSUE TITLE
Test on a paragraph

### ISSUE THREAD

**Issue by Tailor2019** [Calamari-OCR/calamari#301]
Hello!
@ChWick @andbue 
Please can I train calamari on lines of images and testing it on a paragraph?
Please how can I doing this?
Thanks in advance!!

**Comment by andbue** [comment]
As long as you're providing the coordinates of the lines with a PAGE XML file, you can run your model on the page or paragraph image.

**Comment by Tailor2019** [comment]
Thanks a lot for your reply!
@andbue 
But how can I prepare this PAGE XML file?
can you give me un example of this xml file? Does exist a tool that can help preparing these coordinates?
Thanks in advance!

**Comment by andbue** [comment]
Have a look here https://github.com/PRImA-Research-Lab/PAGE-XML
Some tools and libraries:
 http://www.primaresearch.org/tools/Aletheia/
https://github.com/OCR4all/LAREX
https://github.com/qurator-spk/eynollah
https://github.com/OCR4all/OCR4all_helper-scripts/blob/master/ocr4all_helper_scripts/helpers/pagelineseg_helper.py

**Comment by Tailor2019** [comment]
@andbue 
If I have like this paragraph 
![IMG002](https://user-images.githubusercontent.com/47376635/148472772-3ff7c923-02d4-4034-a643-b3a899a7a07a.jpg)
:
How can I proceed for recognizing it with Calamari?
Thanks in advance!

**Comment by andbue** [comment]
As I said before, the image alone won't do it. You need a XML file structured according to the PAGE XML schema containing the line coordinates. How you achieve this is not the business of Calamari-OCR. Maybe the most simple way for you would be to just use Aletheia, this has been proposed here and over there https://github.com/PRImA-Research-Lab/PAGE-XML/issues/30#issuecomment-1006776375 as well.

Please don't try to save time by stealing other people's time e.g. by @-ing all developers you can get hold of at once in a github issue and then just asking them to explain to you the most basic workings of their code. We're doing our best to provide you with documentation for [calamari](https://calamari-ocr.readthedocs.io/en/latest/), it is even included in a GUI at [OCR4all](http://ocr4all.org/en/home.php). The internet is full of blog posts and tutorials explaining how the different steps of text recognition with line based OCR engines (calamari, kraken, ocropus, tesseract...) work. Please, do some reading first and then ask questions directly related to the project, showing that you've read the docs and that you've tried at least some google search on the topic.
