### ISSUE TITLE
calamari-train: Exception 'NoneType' object has no attribute 'astype'

### ISSUE THREAD

**Issue by stefanCCS** [Calamari-OCR/calamari#306]
Version 2.1.5

I have got the follwing expection for all of my training and eval lines (just a small test set):
Call made
`calamari-train --network deep3 --trainer.epochs 1 --train.batch_size 10 --trainer.output_dir SmallDataSet/model-01/ --early_stopping.n_to_go 0 --train.images SmallDataSet/Train/*.png --val.images SmallDataSet/Eval/*.png`

Example Image and GT-File --> see below ..

```
INFO     2022-02-25 09:01:56,266 tfaip.data.pipeline.datapipeli: Preloading: Converting training to raw pipeline.
^MLoading samples:   0%|          | 0/24 [00:00<?, ?it/s]^MLoading samples: 100%|██████████| 24/24 [00:00<00:00, 959.17it/s]
^MApplying data processor CenterNormalizerProcessor:   0%|          | 0/24 [00:00<?, ?it/s]ERROR    2022-02-25 09:01:56,322 calamari_ocr.ocr.dataset.image: 'NoneType' object has no attribute 'astype'
Traceback (most recent call last):
  File "/home/calamariadmin/calamari_venv_37/lib/python3.7/site-packages/calamari_ocr/ocr/dataset/imageprocessors/data_preprocessor.py", line 13, in apply
    return sample.new_inputs(self._apply_single(sample.inputs, sample.meta))
  File "/home/calamariadmin/calamari_venv_37/lib/python3.7/site-packages/calamari_ocr/ocr/dataset/imageprocessors/center_normalizer.py", line 35, in _apply_single
    out, params = self.normalize(data.astype(np.uint8))
AttributeError: 'NoneType' object has no attribute 'astype'
WARNING  2022-02-25 09:01:56,323 calamari_ocr.ocr.dataset.image: There was an unknown error when processing a line image. The line is skipped.
The error was caused by the line with meta data: {'id': 'OCR-D-SEG-LINE-CCS-3-IMG-4084_007804465_00001_TR-19_TR-19_line', 'augmented': False, 'fold_id': -1}.
Please report this as an issue including the meta data, stack trace,  the respective image file and call.
You can ignore this error if it occurs only very rarely, only this particular line will be skipped.
```
![OCR-D-SEG-LINE-CCS-3-IMG-4084_007804465_00001_TR-1_TR-1_line](https://user-images.githubusercontent.com/61045115/155688633-7704a0e8-1e21-4b66-9f08-748fb8f12241.png)
[OCR-D-SEG-LINE-CCS-3-IMG-4084_007804465_00001_TR-1_TR-1_line.gt.txt](https://github.com/Calamari-OCR/calamari/files/8139994/OCR-D-SEG-LINE-CCS-3-IMG-4084_007804465_00001_TR-1_TR-1_line.gt.txt)

![OCR-D-SEG-LINE-CCS-3-IMG-4084_007804465_00001_TR-19_TR-19_line](https://user-images.githubusercontent.com/61045115/155688867-8197e73f-3a96-4987-8bcd-6cb769763318.png)
[OCR-D-SEG-LINE-CCS-3-IMG-4084_007804465_00001_TR-19_TR-19_line.gt.txt](https://github.com/Calamari-OCR/calamari/files/8140005/OCR-D-SEG-LINE-CCS-3-IMG-4084_007804465_00001_TR-19_TR-19_line.gt.txt)

**Comment by stefanCCS** [comment]
Same with version 2.2.1

**Comment by andbue** [comment]
Thanks for the report! Your images are grayscale with an alpha channel, seems like calamari did not expect that... Fixed with 29903c3e31bed5ca2c90d7f0e85fcf16b9dd8e73

**Comment by stefanCCS** [comment]
@andbue : Do you plan to publish a new Release (e.g. 2.2.2) in the near future  (including this bugfix)?

**Comment by andbue** [comment]
Now on pypi: https://pypi.org/project/calamari-ocr/2.2.2/
