### ISSUE TITLE
Error when convert old trained model to latest version model

### ISSUE THREAD

**Issue by WeiHin** [Calamari-OCR/calamari#327]
i got the error as below when want to convert the old trained model that is version 2 to latest version model. below is the error i encounter:

![image](https://user-images.githubusercontent.com/61271158/180726924-70c5bf67-87dc-46b3-80cb-5e237d9a2150.png)

**Comment by andbue** [comment]
Hi, guessing from your screenshot, I think it might be some version mismatch between your tensorflow installation and other requirements, in this case the wrapt package. Maybe a clean installation in a clean venv could work?
