### ISSUE TITLE
calamari/1.0: hold Tensorflow and Protobuf dependencies

### ISSUE THREAD

**Issue by bertsky** [Calamari-OCR/calamari#337]
IIUC ocrd_calamari just [broke](https://github.com/bertsky/ocrd_all/actions/runs/4551641950/jobs/8025960909) because of a new protobuf release. Looking at the requirements.txt for `calamari-ocr==1.0.5` (the latest on that branch), it unconditionally requires `tensorflow` and `protobuf`.

Could we please restrict this, e.g. `protobuf<4.0`, to support 1.x a little longer?

@mikegerber you also mentioned problems with protobuf in Calamari 2 and Python 3.11, but I guess this is unrelated?

**Comment by mikegerber** [comment]
> IIUC ocrd_calamari just [broke](https://github.com/bertsky/ocrd_all/actions/runs/4551641950/jobs/8025960909) because of a new protobuf release. Looking at the requirements.txt for `calamari-ocr==1.0.5` (the latest on that branch), it unconditionally requires `tensorflow` and `protobuf`.
> 
> Could we please restrict this, e.g. `protobuf<4.0`, to support 1.x a little longer?
> 
> @mikegerber you also mentioned problems with protobuf in Calamari 2 and Python 3.11, but I guess this is unrelated?

Yes, with my latest tests I had to downgrade protobuf too, for Calamari 2. Couldn't tell which version was needed though. (Calamari 2 is on hold due to the licensing issues.)

**Comment by mikegerber** [comment]
I've worked around the issue in ocrd_calamari 1.0.6 by requiring protobuf < 4.0, but this should be fixed in Calamari 1.x itself (and in Calamari 2,x if there's still a problem - and only to repeat - we can't currently upgrade to 2.x due to the licensing issues #3)

**Comment by bertsky** [comment]
> I've worked around the issue in ocrd_calamari 1.0.6 by requiring protobuf < 4.0

Oh, so you added [this workaround for the protobuf dep](https://github.com/OCR-D/ocrd_calamari/commit/16a79cead68e1d611ee6184d2fcfd1b1e9a48e5d) and [another workaround for the numpy deprecations](https://github.com/OCR-D/ocrd_calamari/commit/699554dc8a057001674488f3e1a868d3ea7cc130).

So that means now ocrd_calamari and calamari-ocr versions will not be in sync anymore. Shouldn't we rather attempt to solve both problems upstream via PR on the `calamari/1.0` branch and then ask for a v1.0.6 there?

**Comment by mikegerber** [comment]
> > I've worked around the issue in ocrd_calamari 1.0.6 by requiring protobuf < 4.0
> 
> Oh, so you added [this workaround for the protobuf dep](https://github.com/OCR-D/ocrd_calamari/commit/16a79cead68e1d611ee6184d2fcfd1b1e9a48e5d) and [another workaround for the numpy deprecations](https://github.com/OCR-D/ocrd_calamari/commit/699554dc8a057001674488f3e1a868d3ea7cc130).
> 
> So that means now ocrd_calamari and calamari-ocr versions will not be in sync anymore. Shouldn't we rather attempt to solve both problems upstream via PR on the `calamari/1.0` branch and then ask for a v1.0.6 there?

I've removed the numpy/protobuf workarounds in ocrd_calamari and depend on 1.0.x, >= 1.0.6 instead. Tested on Python 3.7-3.11.

(versions in sync? The versions are only accidently identical.)

**Comment by mikegerber** [comment]
I think this issue can be closed now.

**Comment by bertsky** [comment]
Indeed. 

Thanks @andbue and @mikegerber!
