### ISSUE TITLE
Feature Request: fully automatic two step training with data augmentation

### ISSUE THREAD

**Issue by chreul** [Calamari-OCR/calamari#34]
our experiments have shown that, when using data augmentation, a two step training approach is sensible:
1. train on all available lines (real + augmented).
2. refine the models resulting from 1 by training on real lines only and use the outcome of 1 as a starting point.

it would be nice if these training steps could be automatically performed by calamari without requiring any futher input by the user. the auto config proposed in https://github.com/Calamari-OCR/calamari/issues/33 might be helpful :-).

**Comment by ChWick** [comment]
closed by 39ab9676183db39795ae712f3e351e11c6e566dc
