### ISSUE TITLE
Release confusion

### ISSUE THREAD

**Issue by DrKroll** [Calamari-OCR/calamari#347]
I am currently trying to get the calamari engine running and I ran into several confusions. The most important one: Why is your latest release called 1.0.6, while you already had a version called 2.2.2? Thanks!

**Comment by andbue** [comment]
We did an update at the calamari 1 branch because OCR-D is for some reasons stuck with calamari < 2. If you're not using their scripts, calamari 2.2.2 is the better choice.

**Comment by mikegerber** [comment]
I think you can set the latest 2.x release as "Latest". I hope it will then also be the one that shows up at project page level.

![grafik](https://github.com/Calamari-OCR/calamari/assets/34309482/d3581e16-79b5-4b31-8e19-08dabc0cf401)

**Comment by mikegerber** [comment]
Now it's 2.2.2 ;) Thanks @andbue!

**Comment by mikegerber** [comment]
(I think this issue can be closed)
