### ISSUE TITLE
Error during training

### ISSUE THREAD

**Issue by linzhi123** [Calamari-OCR/calamari#38]
TypeError: Failed to convert object of type <class 'tensorflow.python.framework.sparse_tensor.SparseTensor'> to Tensor. Contents: SparseTensor(indices=Tensor("Where:0", shape=(?, 2), dtype=int64), values=Tensor("sub:0", shape=(?,), dtype=int32), dense_shape=Tensor("Shape:0", shape=(2,), dtype=int64)). Consider casting elements to a supported type.

What is the reason, please?

**Comment by ChWick** [comment]
Could you provide more information:
* Operating system
* Calamari version (pypi or github master/dev)
* Training on GPU/CPU
* The full command
* The full stack trace

Thanks!

**Comment by linzhi123** [comment]
Operating system:centos7
Calamari    @@@version:github master
Training on GPU/CPU:GPU,gt 1060

I download the source code on GitHub and run calamari/calamari_ocr/scripts/train.py..
I use tensorflow-gpu 1.4.1. @ChWick

**Comment by linzhi123** [comment]
I also have the same problem with virtual environment   @@installation.
My tensorflow-gpu=1.4.0
@ChWick

**Comment by ChWick** [comment]
@linzhi123 You must upgrade tensorflow to at least v1.6 (newer is better). Please try again and paste the full stack trace if the problem persists.

**Comment by linzhi123** [comment]
ok @ChWick
