### ISSUE TITLE
How to specify the installation of tensorflow as GPU version when installing virtual environment

### ISSUE THREAD

**Issue by linzhi123** [Calamari-OCR/calamari#39]
Hello, when I use virtual environment to install, how do I specify the installation of tensorflow-gpu?

**Comment by ChWick** [comment]
You can uninstall tensorflow and install tensorflow_gpu in your venv:
`pip uninstall tensorflow`
`pip install tensorflow_gpu`

**Comment by linzhi123** [comment]
hank you very much! What version of tensorflow-gpu is specified? @ChWick

**Comment by ChWick** [comment]
by default this will install the current version of tensorflow from pypi (v1.12). Calamari requires at least v1.6
