### ISSUE TITLE
Error after iteration training

### ISSUE THREAD

**Issue by irann93** [Calamari-OCR/calamari#40]
os : win10
python : 3.6
train on cpu
tensorflow version: 1.12.0
install through 'pip install calamari'

I tried to train my own model using the following command :
"calamari-train --files img1.png --max_iters=10" and the following error occured.

> Total time 15.09201717376709s for 9 iterations.
> 2018-11-13 11:55:35.169246: W tensorflow/core/kernels/data/generator_dataset_op.cc:78] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
>          [[{{node PyFunc}} = PyFunc[Tin=[DT_INT64], Tout=[DT_INT64], token="pyfunc_2"](arg0)]]

**Comment by ChWick** [comment]
Your model trained successfully, however the 'shutdown' of Calamari causes an error. I will check this, thanks for you report.

**Comment by ChWick** [comment]
Is fixed with the current upgrade (0.2.2):
`pip install --upgrade calamari-ocr`
