### ISSUE TITLE
A version of data flow on the fly?

### ISSUE THREAD

**Issue by Paul0M** [Calamari-OCR/calamari#41]
Thanks for this open source code!
Succeed training chinese:
![screenshot from 2018-11-15 08-38-35](https://user-images.githubusercontent.com/13173000/48522066-222d0a80-e8b2-11e8-95ab-1d8b162388d3.png)

Wonder if there can be a version to train with data on the fly?
The dataset is pretty large! Right now, I just used a small portion of the whole dataset.

Also checked [37](https://github.com/Calamari-OCR/calamari/issues/37).

I think data flow on the fly would be more practicable instead of dump all data in to RAM.

**Comment by Paul0M** [comment]
Found ways

**Comment by MrOCR** [comment]
@Paul0M Did you solve the 'data flow on the fly' problem?
