### ISSUE TITLE
Parameter problem

### ISSUE THREAD

**Issue by linzhi123** [Calamari-OCR/calamari#43]
Hello, I don't understand the function of whitelist.

**Comment by ChWick** [comment]
For the original paper refer to: https://arxiv.org/abs/1712.05586
The basic idea is: If you train a model on only a few lines of Ground Truth some characters might not be present yet (e. g. mostly some capital letters). Thus, usually the network can only predict characters that are in the GT. However, if you start from a pretrained model that already knows all (or even more) letters you can specify which letters shall be kept (whitelist). By that the newly trained has a chance to predict unseen characters based on the original model.
The `whilelist` parameter expects a list of characters to be kept, e. g. `--whitelist ABCDEFG...`. Alternatively, you can use a text file and the `whitelist_file` parameter.

**Comment by linzhi123** [comment]
thank you very much
