### ISSUE TITLE
Freeze graph

### ISSUE THREAD

**Issue by irann93** [Calamari-OCR/calamari#44]
I wanted to freeze the .ckpt file to .pb model
I had error during loading the .ckpt file using following function

> checkpoint_file = "./output/model_00000050.ckpt"
> saver = tf.train.import_meta_graph("{}.meta".format(checkpoint_file))

And it return me the error
> KeyError: 'LSTMBlockCell'

**Comment by irann93** [comment]
Seems like this guy have an solution but i still face the error

> https://github.com/tensorflow/tensorflow/issues/20732#issuecomment-406959763

Could you please try to implement and see does it work?

**Comment by ChWick** [comment]
Unfortunately, this did not work for me. Particularly, restoring GPU trained models fail with another exception (compare https://github.com/tensorflow/models/issues/2505#issuecomment-432923045).

Thus, our attempt is similar to https://gist.github.com/melgor/41e7d9367410b71dfddc33db34cba85fQ to recreate the graph and then restore the weights:
```python
from calamari_ocr.ocr import Predictor
checkpoint_file = "./output/best.ckpt"
predictor = Predictor(checkpoint=checkpoint_file)
```
