### ISSUE TITLE
General

### ISSUE THREAD

**Issue by MrOCR** [Calamari-OCR/calamari#46]
This is a general topic for Calamari.

**Comment by MrOCR** [comment]
Currently re-testing Calamari .yml installation files, I found some conflicts using the latest Calamari master.

Don't worry, I am working on pushing updated .yml files.

1- Removing the specification of each package version, so that Conda can handle the versions itself.
2-  Stating the version of only the packages that define the rest.

**Comment by MrOCR** [comment]
#50 
- Solved the conflicts by removing the package versions.
- Solved the Tensorflow issue by giving conda `defaults` repo the priority over `conda-forge`.

**Comment by ChWick** [comment]
@MrOCR Should be fixed. Do not forget to test the `--train_data_on_the_fly` parameter.

**Comment by MrOCR** [comment]
Topic: Branch `41-on-the-fly-data-loading` | Error: `Argument list too long`

Calamari-fly is working on smaller samples of 100 images, but when testing on a sample of +1,000,000 images an error message of `Argument list too long` appears, which is normal due to limitations.

@ChWick do you recommend a way to overcome this? or perhaps loading a list using find?
`find -type f -name '*.png' > list.txt`

```
(calamari) home@home-lnx:~/Desktop/Untitled Folder$ calamari-train --train_data_on_the_fly --files ./training_data/*.png
bash: /home/home/anaconda3/envs/calamari/bin/calamari-train: Argument list too long
```
