### ISSUE TITLE
predict_raw : Unknown instance of txts: <class 'tuple'>

### ISSUE THREAD

**Issue by CrazyCrud** [Calamari-OCR/calamari#47]
First of all, I would like to thank you for the work you put in _Calamari_!

I have the following code snippet:

```
image = np.zeros((2, 2, 1))  # placeholder image
images = [image]
dataset = RawDataSet(images=images)

checkpoint = get_path_to_model()
predictor = Predictor(checkpoint=checkpoint)
#  TODO: load via network

prediction_results = predictor.predict_dataset(dataset, progress_bar=False)

for prediction, sample in prediction_results:
    pass
```

The error I get is the following:

>File "[...]\calamari_ocr\ocr\predictor.py", line 132, in predict_dataset
>   for prediction, sample in zip(prediction_results, dataset.samples()):
>  File "[...]\calamari_ocr\ocr\predictor.py", line 158, in predict_raw
>    datas, params = zip(*self.data_preproc.apply(datas, processes=self.processes, 
> progress_bar=progress_bar))
>  File "[...]\calamari_ocr\ocr\data_processing\data_preprocessor.py", line 21, in apply
>    raise Exception("Unknown instance of txts: {}. Supported list and str".format(type(data)))
> Exception: Unknown instance of txts: <class 'tuple'>. Supported list and str

The _zipping_ found in the _predict_dataset_ method transforms the list, respectively the _numpy_-array, into a _tuple_.

`data_params = zip(datas, [None] * len(datas))`

Calamari-version: 0.2.2
Installed via _pip_

Can you give me any advices about that issue?

Thank you!

**Comment by ChWick** [comment]
Thanks! Fixed by fb2feff.
