### ISSUE TITLE
OCR numbers

### ISSUE THREAD

**Issue by hsl20130659** [Calamari-OCR/calamari#49]
it seems that the model can not recognize numbers

**Comment by ChWick** [comment]
Which model did you use?

**Comment by hsl20130659** [comment]
fraktur_19th_century

**Comment by ChWick** [comment]
This model is trained to prediction both characters and numbers. Could you please provide a line of your data where it fails?

**Comment by hsl20130659** [comment]
it writes nothing in the result.txt

**Comment by hsl20130659** [comment]
I use a picture that has numbers and chinese characters

**Comment by ChWick** [comment]
The fraktur 19th century model can only be used for Fraktur fonts: The characters must be similar to https://en.wikipedia.org/wiki/Fraktur.
It might be possible that the model could possibly detect Arabic digits embedded in Chinese fonts, however I can not guarantee that. Do you input a full image or only a single horizontal text line? The latter is required.

**Comment by hsl20130659** [comment]
I put a full image into the network ,my goal is just recognizing the 
numbers and I dont care if there are chinese characters or not.

**Comment by ChWick** [comment]
Calamari can only process single lines, not a full image. You need a separate tool to handle the line segmentation. You can use e. g. https://github.com/tmbdev/ocropy/wiki/Page-Segmentation for the page and line segmentation.

**Comment by hsl20130659** [comment]
my pictures are cropped from ID cards ,the row of birthdays

**Comment by ChWick** [comment]
Solely the row of birthdays? Can you attach a single image file. Maybe you need https://github.com/Calamari-OCR/calamari_models/tree/master/antiqua_modern as model (Modern typographic fonts).

**Comment by hsl20130659** [comment]
[``](https://pan.baidu.com/s/1-NXCjPB5IwufNNfLlO8VrQ)

**Comment by hsl20130659** [comment]
you can test the pictures,and show me the results

**Comment by ChWick** [comment]
This might work, but additional steps are required:
* Crop the bottom area to the content with approximately 3px margin around the text.
* Binarize the image

I manually did those steps and got `(. 1986t 1 t 8 fH` as result for `001.png`.

**Comment by ChWick** [comment]
My manually processed input line:
![0001](https://user-images.githubusercontent.com/6162410/49734431-8b6f2600-fc84-11e8-8b38-3211d93044f5.png)

**Comment by hsl20130659** [comment]
do you mind I make a friend with you ? My qq is 913452977, I think I have something more to ask you ,hehe

**Comment by ChWick** [comment]
You can E-Mail me via christoph.wick@informatik.uni-wuerzburg.de.
