### ISSUE TITLE
Regarding training new models

### ISSUE THREAD

**Issue by YongGuCheng** [Calamari-OCR/calamari#60]
When training a new model, calamari-ocr prints "loss, ler, dt" on the screen (default). 
I understand loss, ler (line error rate). 
What is dt?
How are loss, ler, and dt defined? Or, is there any reference/paper covering these definitions?

Thank you in advance for your help!

**Comment by ChWick** [comment]
* ler = Label Error Rate = #Wrong characters / #Total chars  (sometimes = Character Error Rate)
* Loss = CTC-Loss: No 'real' meaning, its the optimization function.
* dt: Time to process a single line

**Comment by YongGuCheng** [comment]
@ChWick Thank you very much for responding promptly. I have successfully trained a Chinese model. 
Danke schön!
