### ISSUE TITLE
Data load is slow

### ISSUE THREAD

**Issue by erjinzhi2333** [Calamari-OCR/calamari#7]
just single process for data load now ?

**Comment by ChWick** [comment]
The loading of data from a (sequential) HDD is indeed limited to a single thread. One could consider to use multithreading when reading from a SSD.
However, the data preprocessing can and should be parallelized (--num_threads for training and -j for prediction)

**Comment by MrOCR** [comment]
@erjinzhi2333 I'd recommend that you skip the SSD and buy an M.2 NVME instead, you will get +3000MB/s Read & 2500MB/s Write. They are almost same price, 
Note that you will need PCIe 3.0 x4 in your Mobo.
