### ISSUE TITLE
train Calamari with simple LSTM 

### ISSUE THREAD

**Issue by HounaidaMoalla** [Calamari-OCR/calamari#72]
Dear @ChWick
Please, if I want to execute Calamari with only one layer LSTM , is the following command correct :

calamari-train --files DatasetPath –network lstm=200 --checkpoint_frequency 1000 --output_dir modelsLSTM200

Thank you

**Comment by ChWick** [comment]
This is correct! However note, that Calamari always used Bidirectional LSTMs,thus in fact, there are 2 LSTM layers each with 200 hidden nodes, the output is concatenated. A fully connected layer (applied to each horizontal pixel = time step) maps to the alphabet size afterwards.

**Comment by HounaidaMoalla** [comment]
Thank you for the answer, but when I check the savedModel.json, I find the network layers contain the same architecture then the deepNetwork architecture (CNN-CNN-LSTM-CTC). Can you tell me what's means.
And where can I find weight values of the trained model.
thank you so much

**Comment by ChWick** [comment]
I can not confirm this. When setting `--network lstm=100` I get a model with only one LSTM layer with 100 nodes:
```json
"network": {
      "layers": [
        {
          "type": "LSTM",
          "hiddenNodes": 100
        }
      ],
      "solver": "ADAM_SOLVER",
      "features": 48,
      "classes": 66,
      "backend": {
        "cudnn": true
      },
      "ctcMergeRepeated": true,
      "learningRate": 0.0010000000474974513
    },
```
(excerpt from lstm100.ckpt.json)
