### ISSUE TITLE
Prediction Confidence

### ISSUE THREAD

**Issue by bjmrevilla** [Calamari-OCR/calamari#76]
Hi @ChWick. I just want to ask a few questions regarding the confidence of predictions in Calamari. 

- How do we get the confidence of a prediction given one strip of image? 
- How do we get the confidence of a single prediction made by an ensemble of models? 

Thanks! and Awesome work BTW.

**Comment by ChWick** [comment]
Hi, @bjmrevilla. There are two options.

* Call the `Predictor` directly in python code, or
* Write `--extended_prediction_data`

In both cases you have access to a [Prediction](https://github.com/Calamari-OCR/calamari/blob/8b5a8bedaeb5e8bc35878d7ae39430a5c285c9ec/calamari_ocr/proto/calamari.proto#L259) data structure (either already in memory, or as file).
In this prediction all relevant data such as the [full probability matrix](https://github.com/Calamari-OCR/calamari/blob/8b5a8bedaeb5e8bc35878d7ae39430a5c285c9ec/calamari_ocr/proto/calamari.proto#L251) or the [individual character confidences](https://github.com/Calamari-OCR/calamari/blob/8b5a8bedaeb5e8bc35878d7ae39430a5c285c9ec/calamari_ocr/proto/calamari.proto#L235) are stored.

The parameter for `calamari-predict` is `--extended_prediction_data` and you need to set `--extended_prediction_data_format pred` if you want the huge probability matrix to be written.
To read the generated `.pred` files, refer [here](https://github.com/Calamari-OCR/calamari/blob/8b5a8bedaeb5e8bc35878d7ae39430a5c285c9ec/calamari_ocr/scripts/pred_to_json.py#L22)

Alternatively, create a custom `Predictor`:
```python
from calamari_ocr.ocr import Predictor, create_dataset, DataSetType, DataSetMode

# Load (only once)
predictor = Predictor('PATH_TO_THE_MODEL_WITHOUT_EXT')

# Predict
data = create_dataset(
  DataSetType.RAW,  # if you already have np.arrays or DataSetType.File to load from the filesystem
  DataSetMode.PREDICT,
  images=[raw_image_or_path_to_image],
)
for prediction in predictor.predict_dataset(data):
    pass
```

**Comment by bjmrevilla** [comment]
Thanks @ChWick. I appreciate the links and the code. Closing this now.

**Comment by alexander-winkler** [comment]
Sorry to reopen this, but I was wondering if the above solutions are still working (v2.1.1). I'd like to get the confidences for single lines.

The command line parameter `--extended_prediction_data` needs one argument:

```
calamari-predict: error: argument --extended_prediction_data: expected one argument
```

The API modules appear to have changed.

Thank you!

**Comment by andbue** [comment]
In https://github.com/Calamari-OCR/calamari/pull/249 I try to fix the broken paths for PageXML. Now setting `--extended_prediction_data True` creates a directory named after each image file and containing [line_id].json with the extended predictions.

@ChWick: is it possible in paiargparse to turn boolean arguments into normal command line paramenters without arguments, i.e. when present, True, else False? This would only allow for default=False, though. Maybe the parameter could automatically be inverted by appending something like "_off" or prepending "no_" when default=True?
