### ISSUE TITLE
Implementing Dilated Convolution Layer 

### ISSUE THREAD

**Issue by thak123** [Calamari-OCR/calamari#80]
How can Dilated convolution be employed in the current setting. ?

Came across this repository doing similar ..
https://github.com/MaybeShewill-CV/CRNN_Tensorflow

**Comment by chreul** [comment]
most of the required code has already been added [here](https://github.com/Calamari-OCR/calamari/blob/master/calamari_ocr/ocr/backends/tensorflow_backend/tensorflow_model.py). we will soonish extend the network specification language so that it can be used and evaluated.

**Comment by chreul** [comment]
example usage: --network cnn=40:3x3,pool=2x2,cnn=60:3x3,pool=2x2,**db=120:4:3x3**,lstm=200,dropout=0.5
extends the default network by a dilated block consisting of four parallel CNNs with dilation values of 1 (default CNN), 2, 3, and 4

this exact setup did not yield notable improvements for me. more testing required, though.
