### ISSUE TITLE
Prediction returns capital letters for small letters

### ISSUE THREAD

**Issue by thak123** [Calamari-OCR/calamari#83]
I have trained a model on default network but the prediction seems to return capital letters for small letters 

This is my char set.

{'p', ',', 'q', 'U', 'é', '6', 'C', '-', 'm', 'c', ' ', '/', 'J', 'N', 'h', 'b', 'f', '2', 'R', '9', 'k', '3', 'i', '&', 'y', 'j', 'w', 'ë', 's', '4', 'O', 'v', 'H', 'n', 'S', 'Y', '5', 'a', '(', 'P', ')', 'E', 'l', 'o', 'T', 'B', 'z', 'I', 'K', 'V', '0', 'ä', '.', 'u', 'F', 'd', '[', 'x', "'", 'A', 'g', 'L', 'M', 'e', 'Q', 'W', '8', '7', 't', '%', ']', 'è', 'D', '1', '$', 'r', 'G'}

can anyone help me in debugging this issue ? Thanks

**Comment by ChWick** [comment]
can you provide some lines of your GT and your prediction data? I guess there might be the problem.
