### ISSUE TITLE
Ability to use calamari as a library

### ISSUE THREAD

**Issue by synap5e** [Calamari-OCR/calamari#85]
Support for using calamari as a library with a trained model is a little difficult and does not appear to be documented. 

Some use cases (such as my own) could benefit from using calamari as a library inside an application, or to be able to serve calamari-backed OCR e.g. over HTTP. Specifically in these use cases the multithreaded nature of calamari is likely not desired.
I have been able to solve this (script provided for the benefit of people searching for similar functionality), but it's a bit of a hack. 

Apologies if there is some way of doing this that I missed and thanks for this tool 😄 

```python
predictor = Predictor(checkpoint='./models/best.ckpt', batch_size=1, processes=1)
def predict(images: List[np.ndarray]) -> Iterator[Tuple[str, float]]:
    processed_images = np.array([predictor.data_preproc._apply_single(i)[0].astype(np.float) / 255. for i in images])
    for result in predictor.network.predict_raw(processed_images, [processed_images.shape[1] for im in images]):
        result.softmax = np.roll(result.softmax, 1, axis=1)
        l, s = result.softmax, result.output_length
        result.decoded = predictor.network.ctc_decoder.decode(l[:s])
        prediction = PredictionResult(
            result.decoded,
            codec=predictor.codec,
            text_postproc=predictor.text_postproc,
            out_to_in_trans=OutputToInputTransformer(None, predictor.network),
            data_proc_params=None,
            ground_truth=result.ground_truth
        )
        yield prediction.sentence, prediction.prediction.avg_char_probability 
```

**Comment by ChWick** [comment]
This is documented (indirectly) in the [Wiki](https://github.com/Calamari-OCR/calamari/wiki/Prediction-(extended-data)#call-the-predictor-in-python).

Use a `RawDataset` and apply the predictor:
```python
from calamari_ocr.ocr import Predictor, create_dataset, DataSetType, DataSetMode

# Load (only once)
predictor = Predictor('PATH_TO_THE_MODEL_WITHOUT_EXT')

# Predict
data = create_dataset(
  DataSetType.RAW,  # if you already have np.arrays or DataSetType.File to load from the filesystem
  DataSetMode.PREDICT,
  images=[raw_image_or_path_to_image],
)
for prediction in predictor.predict_dataset(data):
    pass
```

**Comment by synap5e** [comment]
Unfortunately this still starts multiple processes, which is what I was avoiding with my method.
Is there a way to disable this behavior and run all in the main thread?

`predict_input_dataset` with `RawInputDataset` seems to do this, but I cannot work out how to create a `RawInputDataset` correctly.
