### ISSUE TITLE
Regarding --checkpoint path_to_model.ckpt

### ISSUE THREAD

**Issue by Raviteja1996** [Calamari-OCR/calamari#98]
Hi I just installed calamari-OCR. I wanted to test it on a simple image, then I saw that **--checkpoint path_to_model.ckpt**. Should we compulsorily train any model before doing calamari-predict. I saw in some of the issues **calamari_models/default/ModernEnglish.ckpt**. But that is not present now. I am new to all these, can you please help me out in this. Thank you.

**Comment by ChWick** [comment]
Pretrained models can be downloaded [here](https://github.com/Calamari-OCR/calamari_models).
E. g. for text printed in modern English (Latin letters) use `--checkpoint calamari_models/antiqua_modern/
0.ckpt`. To gain better results you can predict and vote using all 5 models `--checkpoint calamari_models/antiqua_modern/*.ckpt`.
No additional training is required for these models.

**Comment by Raviteja1996** [comment]
Hi, thanks for the reply now I am able to run. But when I did nvidia-smi there is no usage of GPU. And also when I run its showing **Using CUDNN compatible LSTM backend on CPU**. Is there anything else i need to do to run i GPU

**Comment by ChWick** [comment]
Did you install `tensorflow_gpu`? If not, run:
```
pip uninstall tensorflow
pip install tensorflow_gpu
```
For further information refer to the [tensorflow docs](https://www.tensorflow.org/install/gpu)

**Comment by kmahyyg** [comment]
One-more off-topic question:

how many checkpoints it will kept in disk maximum? seems that is infinite...... That's really a huge disk cost......

**Comment by ChWick** [comment]
@kmahyyg you can specify the frequency when to write checkpoints, e.g.:
* `--checkpoint_frequency 0.5` to write a checkpoint each half epoch
* `--checkpoint_frequency 10000` to write a checkpoint every 10,000 iterations
* `--checkpoint_frequency 0` to not write any checkpoints at all
